using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

namespace Sharq.Core.Editor
{
    /// <summary>
    /// Turns a <see cref="SusFontAsset"/> into the USS override sheet that actually carries a
    /// project's typefaces through the SUS cascade.
    ///
    /// Why this exists (T-2767 / D-069 / R120): SUS declares every typeface in USS, and USS is the
    /// only layer a buyer, a theme or a skin can override. Unity has no public API to author a
    /// StyleSheet or to set a USS custom property from C# at runtime, so a font set filled in the
    /// Inspector cannot be pushed onto the tree at run time without writing an INLINE style - and
    /// an inline style outranks every USS rule, which is precisely what R120 forbids. So the font
    /// set is resolved ONCE here, in the Editor, into
    /// <c>Assets/Resources/SusRuntime/_font.uss</c>: a project-side override sheet that shadows
    /// the packaged one and redefines the <c>--sus-font-family-*</c> hooks the package sheet
    /// already reads.
    ///
    /// The generated file is fully owned by this exporter - it is rewritten on every export and
    /// carries <see cref="Marker"/> in its header so a hand-written sheet is never clobbered
    /// silently.
    /// </summary>
    public static class SusFontUssExporter
    {
        /// <summary>Default destination: the project-side twin of the packaged font sheet.</summary>
        public const string DefaultTargetPath = "Assets/Resources/SusRuntime/_font.uss";

        /// <summary>Header line that marks the file as generated by this exporter.</summary>
        public const string Marker = "sus:generated-by SusFontUssExporter";

        /// <summary>Font-set slot -> the USS hook the packaged <c>_font.uss</c> reads for it.</summary>
        private static readonly (string Token, string Slot)[] Slots =
        {
            ("--sus-font-family-regular", "Regular"),
            ("--sus-font-family-medium", "Medium"),
            ("--sus-font-family-bold", "Bold"),
            ("--sus-font-family-light", "Light"),
            ("--sus-font-family-heading", "Heading"),
            ("--sus-font-family-mono", "Mono"),
            ("--sus-font-family-condensed", "Condensed"),
        };

        [MenuItem("Window/SUS/Fonts/Export Font Set to USS", false, 3)]
        private static void ExportSelected()
        {
            var asset = ResolveAsset(out var problem);
            if (asset == null)
            {
                EditorUtility.DisplayDialog("SUS - Export Font Set to USS", problem, "OK");
                return;
            }

            if (File.Exists(DefaultTargetPath) && !IsGenerated(DefaultTargetPath))
            {
                var overwrite = EditorUtility.DisplayDialog(
                    "SUS - Export Font Set to USS",
                    $"{DefaultTargetPath} already exists and was not written by this exporter.\n\n" +
                    "Overwriting replaces your hand-written font override sheet.",
                    "Overwrite", "Cancel");
                if (!overwrite) return;
            }

            var written = Export(asset, DefaultTargetPath, out var exported, out var skipped);
            AssetDatabase.ImportAsset(written, ImportAssetOptions.ForceUpdate);

            var tail = skipped.Count == 0 ? "" : $" Empty slots left to the SUS default: {string.Join(", ", skipped)}.";
            Debug.Log($"[SusFontUssExporter] Wrote {written} from '{asset.name}' - " +
                      $"{exported.Count} family token(s): {string.Join(", ", exported)}.{tail} " +
                      "Enter Play mode (or reimport) for the panel to pick the sheet up.");
        }

        /// <summary>
        /// Writes the override sheet for <paramref name="asset"/> to <paramref name="targetPath"/>
        /// (project-relative) and returns that path. <paramref name="exported"/> lists the slots
        /// that produced a declaration; <paramref name="skipped"/> lists the slots left empty (the
        /// packaged fallback keeps serving those).
        /// </summary>
        public static string Export(SusFontAsset asset, string targetPath, out List<string> exported, out List<string> skipped)
        {
            exported = new List<string>();
            skipped = new List<string>();

            var sb = new StringBuilder();
            sb.AppendLine("/* SUS font override sheet");
            sb.AppendLine($"   {Marker}");
            sb.AppendLine($"   Source font set: {AssetDatabase.GetAssetPath(asset)}");
            sb.AppendLine();
            sb.AppendLine("   Do not edit by hand - re-export from Window > SUS > Fonts > Export Font Set to USS.");
            sb.AppendLine("   This sheet shadows the packaged Resources/SusRuntime/_font.uss and redefines only the");
            sb.AppendLine("   --sus-font-family-* hooks, so every rule that reads --font-family-* (component styles,");
            sb.AppendLine("   the .sus-font-* marker classes, skins) follows without any C# call. */");
            sb.AppendLine();
            sb.AppendLine(":root {");

            foreach (var (token, slot) in Slots)
            {
                var url = UrlFor(SlotValue(asset, slot));
                if (url == null) { skipped.Add(slot); continue; }
                sb.AppendLine($"    {token}: {url};");
                exported.Add(slot);
            }

            sb.AppendLine("}");

            var dir = Path.GetDirectoryName(targetPath);
            if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);
            File.WriteAllText(targetPath, sb.ToString());
            return targetPath;
        }

        /// <summary>The <see cref="FontDefinition"/> a named slot holds on <paramref name="asset"/>.</summary>
        private static FontDefinition SlotValue(SusFontAsset asset, string slot) => slot switch
        {
            "Regular" => asset.Regular,
            "Medium" => asset.Medium,
            "Bold" => asset.Bold,
            "Light" => asset.Light,
            "Heading" => asset.Heading,
            "Mono" => asset.Mono,
            "Condensed" => asset.Condensed,
            _ => default,
        };

        /// <summary>
        /// USS <c>url()</c> for the font behind <paramref name="fd"/> - the SDF FontAsset when
        /// present, the legacy Font otherwise. Null when the slot is empty or the object has no
        /// asset path (a runtime-created font cannot be named in USS).
        /// </summary>
        private static string UrlFor(FontDefinition fd)
        {
            Object obj = fd.fontAsset != null ? (Object)fd.fontAsset : fd.font;
            if (obj == null) return null;
            var path = AssetDatabase.GetAssetPath(obj);
            if (string.IsNullOrEmpty(path)) return null;
            // USS resolves a project-root path when it starts with '/'.
            return $"url(\"/{path}\")";
        }

        /// <summary>True when <paramref name="path"/> was written by this exporter.</summary>
        private static bool IsGenerated(string path)
        {
            foreach (var line in File.ReadLines(path))
                if (line.Contains(Marker)) return true;
            return false;
        }

        /// <summary>
        /// The font set to export: the selected one, or the project's only one. Fills
        /// <paramref name="problem"/> with what the user has to do when neither applies.
        /// </summary>
        private static SusFontAsset ResolveAsset(out string problem)
        {
            problem = null;
            if (Selection.activeObject is SusFontAsset selected) return selected;

            var guids = AssetDatabase.FindAssets("t:SusFontAsset");
            if (guids.Length == 1)
                return AssetDatabase.LoadAssetAtPath<SusFontAsset>(AssetDatabase.GUIDToAssetPath(guids[0]));

            problem = guids.Length == 0
                ? "No SusFontAsset in this project. Create one via Assets > Create > SUS > Font Set, " +
                  "assign your typefaces, then run this again."
                : $"{guids.Length} font sets found. Select the SusFontAsset you want to export in the " +
                  "Project window, then run this again.";
            return null;
        }
    }
}
