# Regenerates Editor/Setup/Starter~/Generated/HomeScreen.g.cs from HomeScreen.sharq
# and commits nothing — run before pushing starter template changes.
#
# Usage (from anywhere):
#   powershell -NoProfile -File sus-core/Tools~/refresh-starter-generated.ps1

$ErrorActionPreference = 'Stop'
$coreRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
$starter = Join-Path $coreRoot 'Editor\Setup\Starter~'
$bootstrapProj = Join-Path $PSScriptRoot 'SharqBootstrap\SharqBootstrap.csproj'

if (-not (Test-Path (Join-Path $starter 'HomeScreen.sharq'))) {
    throw "Missing HomeScreen.sharq in $starter"
}
if (-not (Test-Path $bootstrapProj)) {
    throw "Missing SharqBootstrap project: $bootstrapProj"
}

$work = Join-Path $env:TEMP ("sus-starter-gen-" + [guid]::NewGuid().ToString('N'))
$assets = Join-Path $work 'Assets'
New-Item -ItemType Directory -Force -Path $assets | Out-Null

$sharqDir = Join-Path $assets 'Starter'
$genDir = Join-Path $assets 'Starter\Generated'
New-Item -ItemType Directory -Force -Path $genDir | Out-Null
Copy-Item (Join-Path $starter 'HomeScreen.sharq') (Join-Path $sharqDir 'HomeScreen.sharq')

$config = @{
    SharqDirectory     = 'Assets/Starter'
    GeneratedDirectory = 'Assets/Starter/Generated'
    ResourcesDirectory = 'Assets/Starter/Generated/Resources/SusRuntime'
} | ConvertTo-Json
Set-Content -Path (Join-Path $assets 'sus.config.json') -Value $config -Encoding utf8

Push-Location $work
try {
    Write-Host "[refresh-starter] Running SharqBootstrap…"
    dotnet run --project $bootstrapProj -- $work
    if ($LASTEXITCODE -ne 0) { throw "SharqBootstrap failed ($LASTEXITCODE)" }

    $src = Join-Path $genDir 'HomeScreen.g.cs'
    if (-not (Test-Path $src)) { throw "Expected output missing: $src" }

    $destDir = Join-Path $starter 'Generated'
    New-Item -ItemType Directory -Force -Path $destDir | Out-Null
    Copy-Item $src (Join-Path $destDir 'HomeScreen.g.cs') -Force
    # Stable path in the auto-generated header (avoids temp-dir noise in git diffs)
    $out = Join-Path $destDir 'HomeScreen.g.cs'
    $text = [IO.File]::ReadAllText($out)
    $text = [regex]::Replace($text,
        '// Auto-generated by SharqSourceGenerator from .*',
        '// Auto-generated by SharqSourceGenerator from Editor/Setup/Starter~/HomeScreen.sharq')
    [IO.File]::WriteAllText($out, $text)
    Write-Host "[refresh-starter] Wrote Editor/Setup/Starter~/Generated/HomeScreen.g.cs"
}
finally {
    Pop-Location
    Remove-Item -Recurse -Force $work -ErrorAction SilentlyContinue
}
