using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UIElements;

namespace Sharq.Core
{
    /// <summary>
    /// Controls when WatchEffect callbacks are executed relative to Unity UI Toolkit layout.
    /// </summary>
    public enum FlushMode
    {
        /// <summary>Runs immediately on prop change, batched once per frame. Default.</summary>
        PreLayout = 0,

        /// <summary>Defers execution until after UI Toolkit layout pass.
        /// Use when the effect reads worldBound / resolvedStyle.</summary>
        PostLayout = 1,
    }

    /// <summary>
    /// Base class for all Sharq UI components. Extends Unity's VisualElement with
    /// Vue-like reactivity, lifecycle hooks, event system, slots, and bind helpers.
    ///
    /// The Build() method is generated by the Sharq Source Generator from .sharq files.
    /// </summary>
    public abstract partial class SusComponent : VisualElement
    {
        // ─── Reactivity helpers ───────────────────────────────────────────

        /// <summary>Create a reactive property.</summary>
        protected Prop<T> P<T>(T initial = default) => new(initial);

        /// <summary>Create a computed (derived) property.</summary>
        protected Computed<T> C<T>(Func<T> fn) => new(fn);

        /// <summary>
        /// Watch a Prop for changes. Returns an IDisposable handle;
        /// disposing it unsubscribes the watcher.
        /// </summary>
        protected WatchHandle Watch<T>(Prop<T> source, Action<T, T> callback)
        {
            if (source == null) throw new ArgumentNullException(nameof(source));
            if (callback == null) throw new ArgumentNullException(nameof(callback));

            source.Changed += callback;
            var h = new WatchHandle(() => source.Changed -= callback);
            TrackBinding(h);
            return h;
        }

        /// <summary>
        /// Watch a Prop for changes, registering the handle in an EffectScope.
        /// The scope owns the handle — calling scope.Dispose() unsubscribes.
        /// </summary>
        protected WatchHandle Watch<T>(Prop<T> source, Action<T, T> callback, EffectScope scope)
        {
            if (scope == null) throw new ArgumentNullException(nameof(scope));
            var h = Watch(source, callback);
            scope.Register(h);
            return h;
        }

        /// <summary>
        /// Create an EffectScope for grouping subscriptions.
        /// Analogous to Vue's effectScope(). Disposing the scope unsubscribes
        /// all watches registered through Watch(prop, cb, scope).
        /// </summary>
        protected EffectScope CreateScope() => new();

        /// <summary>
        /// Shared reactive primitive. Runs fn inside DependencyTracker.Track,
        /// subscribes to all reactive sources (Prop/Computed) read in fn,
        /// and re-runs fn on any invalidation via batched ScheduleBindUpdate.
        /// This is the single source of truth for all reactivity in sus-core.
        /// </summary>
        private WatchHandle ReactiveEffect(Action fn)
        {
            var subs = new System.Collections.Generic.List<IDisposable>();

            void Run()
            {
                foreach (var s in subs) s.Dispose();
                subs.Clear();

                using (DependencyTracker.Track(src =>
                    subs.Add(src.SubscribeInvalidate(() => ScheduleBindUpdate(Run)))))
                {
                    fn();
                }
            }

            Run();
            return new WatchHandle(() =>
            {
                foreach (var s in subs) s.Dispose();
                subs.Clear();
            });
        }

        /// <summary>
        /// Auto-tracking effect. Runs fn immediately, then auto-reruns when any Prop&lt;T&gt;
        /// or Computed&lt;T&gt; read inside fn changes. Equivalent to Vue's watchEffect().
        ///
        /// Example:
        /// <code>
        /// WatchEffect(() => {
        ///     var hp = Health.Value;
        ///     var max = MaxHealth.Value;
        ///     label.text = $"{hp}/{max}";
        /// });
        /// </code>
        /// </summary>
        protected WatchHandle WatchEffect(Action fn)
        {
            if (fn == null) throw new ArgumentNullException(nameof(fn));
            var h = ReactiveEffect(fn);
            TrackBinding(h);
            return h;
        }

        /// <summary>
        /// Auto-tracking effect with flush mode.
        ///
        /// <list type="bullet">
        /// <item><b>PreLayout</b> (default): runs immediately on prop change,
        ///   batched once per frame. Use for data mutations, text updates.</item>
        /// <item><b>PostLayout</b>: defers execution until after Unity UI Toolkit
        ///   completes its layout pass. Use when fn reads worldBound / resolvedStyle.</item>
        /// </list>
        ///
        /// Analogous to Vue watchPostEffect() / React useLayoutEffect.
        /// <code>
        /// WatchEffect(() => {
        ///     PositionSlider(_slider.worldBound.width);
        /// }, FlushMode.PostLayout);
        /// </code>
        /// </summary>
        protected WatchHandle WatchEffect(Action fn, FlushMode flush)
        {
            if (fn == null) throw new ArgumentNullException(nameof(fn));

            if (flush == FlushMode.PostLayout)
            {
                var h = ReactiveEffectPostLayout(fn);
                TrackBinding(h);
                return h;
            }

            return WatchEffect(fn);
        }

        private WatchHandle ReactiveEffectPostLayout(Action fn)
        {
            var subs = new System.Collections.Generic.List<IDisposable>();

            void Run()
            {
                foreach (var s in subs) s.Dispose();
                subs.Clear();

                using (DependencyTracker.Track(src =>
                    subs.Add(src.SubscribeInvalidate(() => ScheduleBindUpdate(Run)))))
                {
                    // Defer execution to after Unity UI Toolkit layout pass
                    schedule.Execute(fn).ExecuteLater(0);
                }
            }

            Run();
            return new WatchHandle(() =>
            {
                foreach (var s in subs) s.Dispose();
                subs.Clear();
            });
        }

        // ─── Binding lifecycle ────────────────────────────────────────────

        private readonly List<WatchHandle> _bindings = new();

        // ─── Batched bind update scheduling ────────────────────────────────

        private readonly HashSet<Action> _pendingBindActions = new();
        private IVisualElementScheduledItem _bindScheduleItem;

        /// <summary>
        /// Batches a bind-update action to execute once per frame.
        /// De-duplicates: same Action is only queued once.
        /// </summary>
        private void ScheduleBindUpdate(Action apply)
        {
            _pendingBindActions.Add(apply);
            _bindScheduleItem ??= schedule.Execute(ApplyAllBindUpdates);
            _bindScheduleItem.ExecuteLater(0);
        }

        private void ApplyAllBindUpdates()
        {
            if (_pendingBindActions.Count == 0) return;
            // Snapshot and clear to allow re-registration during execution
            var actions = new List<Action>(_pendingBindActions);
            _pendingBindActions.Clear();
            foreach (var action in actions)
                action();
        }

        /// <summary>
        /// Creates a WatchHandle for manual subscription tracking.
        /// Use when you need to TrackBinding() for non-standard callbacks
        /// (e.g. Controller.Errors.Changed) that can't use Bind* methods.
        /// </summary>
        protected static WatchHandle CreateWatchHandle(Action unsubscribe)
        {
            return new WatchHandle(unsubscribe);
        }

        /// Registers a binding's WatchHandle so it can be disposed on detach.
        /// Called by all Bind* methods and Watch/WatchEffect.
        /// </summary>
        protected void TrackBinding(WatchHandle h)
        {
            if (h != null) _bindings.Add(h);
        }

        private void DisposeAllBindings()
        {
            for (int i = _bindings.Count - 1; i >= 0; i--)
                _bindings[i].Dispose();
            _bindings.Clear();
            _eventHandlers?.Clear();
        }

        // ─── Breakpoint Service ───────────────────────────────────────────

        /// <summary>
        /// Reactive breakpoint service — tracks screen width and exposes
        /// IsMobile / IsTablet / IsDesktop computed properties.
        /// Lazy-initialized: first access gets or creates the shared
        /// per-root service via SusBreakpointService.For(this).
        /// </summary>
        public SusBreakpointService BreakpointService
        {
            get
            {
                if (_breakpointService == null)
                    _breakpointService = SusBreakpointService.For(this);
                return _breakpointService;
            }
            protected set => _breakpointService = value;
        }
        private SusBreakpointService _breakpointService;

        // ─── Click Audit ───────────────────────────────────────────────────

        /// <summary>
        /// Sets a human-readable description of the component for ClickAuditService.
        /// Call once in Created(). When set, every ClickEvent on this element
        /// is checked by the audit (Editor / Development Build only).
        ///
        /// Example:
        /// <code>
        /// protected override void Created()
        /// {
        ///     SetClickAuditDescription("MainMenu.FightButton");
        ///     // ...
        /// }
        /// </code>
        /// </summary>
        protected void SetClickAuditDescription(string description)
        {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
            _clickAuditDescription = description;
#endif
        }

#if UNITY_EDITOR || DEVELOPMENT_BUILD
        /// <summary>
        /// Logs a warning if the click was blocked by a guard condition.
        /// Call inside a ClickEvent handler on early return.
        ///
        /// Example:
        /// if (Disabled.Value) {
        ///     AuditClickBlocked("Disabled");
        ///     return;
        /// }
        /// </summary>
        protected void AuditClickBlocked(string reason)
        {
            var desc = _clickAuditDescription ?? GetType().Name;
            UnityEngine.Debug.LogWarning($"[CallbackAudit] '{desc}' click blocked: {reason}");
        }

        /// <summary>
        /// Logs if the handler ran but took longer than the threshold ms.
        /// </summary>
        protected double AuditClickStart()
        {
            return UnityEngine.Time.realtimeSinceStartupAsDouble;
        }

        protected void AuditClickEnd(double startTime, string action = "OnClick")
        {
            var elapsed = (UnityEngine.Time.realtimeSinceStartupAsDouble - startTime) * 1000.0;
            if (elapsed > 50.0)
            {
                var desc = _clickAuditDescription ?? GetType().Name;
                UnityEngine.Debug.LogWarning($"[CallbackAudit] '{desc}' {action} took {elapsed:F1}ms");
            }
        }
#endif

        // ─── Overlay convenience methods ──────────────────────────────────

        /// <summary>
        /// Adds an element to the nearest OverlayHost in the visual tree.
        /// Traverses up to root to find or create the overlay container.
        /// Returns null if no root panel is attached.
        /// </summary>
        protected OverlayEntry AddToOverlay(VisualElement element, OverlayCategory category,
            bool dismissOnClickOutside = false, System.Action onDismiss = null)
        {
            if (element == null) return null;
            if (panel == null) return null;

            var root = panel.visualTree;
            var overlay = SusBootstrap.GetOrCreateOverlay(root);
            return overlay.AddToOverlay(element, category, dismissOnClickOutside, onDismiss);
        }

        /// <summary>
        /// Removes an element from the nearest OverlayHost.
        /// </summary>
        protected void RemoveFromOverlay(VisualElement element)
        {
            if (element == null || panel == null) return;
            var root = panel.visualTree;
            if (root.childCount == 0) return;
            var last = root.ElementAt(root.childCount - 1);
            if (last is OverlayHost overlay)
                overlay.RemoveFromOverlay(element);
        }

        // ─── Generated by Source Generator ────────────────────────────────

        /// <summary>
        /// Builds the visual tree. Implemented by the Source Generator
        /// in a partial class from .sharq &lt;template&gt; section.
        /// </summary>
        protected abstract void Build();

        // ─── Scoped CSS ───────────────────────────────────────────────────

        /// <summary>
        /// Applies a scoped CSS class to this element for isolation.
        /// Called by generated Build() when &lt;style scoped&gt; is present.
        /// </summary>
        protected void ApplyScopedAttribute(string hash)
        {
            AddToClassList(hash);
        }

        // ─── USS Auto-loading ────────────────────────────────────────────

#if UNITY_EDITOR
        /// <summary>
        /// Editor-only development fallback dirs for companion USS resolution when the
        /// Resources copy is missing/stale. Defaults to the current project's Sharq output
        /// and sus-core's own Generated dir. Downstream packages register their own
        /// Generated dir via <see cref="RegisterEditorGeneratedDir"/> — core has
        /// no hardcoded knowledge of them.
        /// </summary>
        private static readonly System.Collections.Generic.List<string> s_editorGeneratedDirs = new()
        {
            "Assets/SusUI/Generated",                                 // project-local
            "Packages/com.sharq-it.sus.core/Runtime/Generated",      // core's own (self-reference OK)
        };

        /// <summary>
        /// Registers an editor-only fallback directory (AssetDatabase path, e.g.
        /// "Packages/com.example.ui/Runtime/Generated") for companion USS lookup.
        /// Idempotent. Editor-only — production builds resolve via Resources.
        /// </summary>
        public static void RegisterEditorGeneratedDir(string assetDir)
        {
            if (string.IsNullOrEmpty(assetDir)) return;
            if (!s_editorGeneratedDirs.Contains(assetDir))
                s_editorGeneratedDirs.Add(assetDir);
        }
#endif

        /// <summary>
        /// Loads all companion USS files for this component from Resources/SusRuntime/.
        /// Tries: {ClassName}_static.g.uss, {ClassName}_scoped.g.uss, {ClassName}.g.uss
        /// Called automatically from generated Build().
        /// </summary>
        protected void LoadCompanionStyleSheets() => LoadCompanionStyleSheets(null);

        /// <summary>
        /// Loads companion USS, optionally restricted to specific suffixes
        /// ("_static.g" / "_scoped.g" / ".g") for partial hot reload.
        /// </summary>
        private void LoadCompanionStyleSheets(System.Collections.Generic.ICollection<string> onlySuffixes)
        {
            var name = GetType().Name;
            string[] suffixes = { "_static.g", "_scoped.g", ".g" };
            foreach (var suf in suffixes)
            {
                if (onlySuffixes != null && !onlySuffixes.Contains(suf)) continue;
                var fileName = suf.Length > 0 ? $"{name}{suf}" : name;
                var sheet = UnityEngine.Resources.Load<StyleSheet>(SusBootstrap.ResourcePath + fileName);

#if UNITY_EDITOR
                // Development fallback: Resources is the primary path; when the copy is
                // missing/stale, scan the registered Generated dirs (project + packages).
                if (sheet == null)
                {
                    foreach (var dir in s_editorGeneratedDirs)
                    {
                        sheet = UnityEditor.AssetDatabase.LoadAssetAtPath<StyleSheet>($"{dir}/{fileName}.uss");
                        if (sheet != null) break;
                    }
                }
#endif

                if (sheet != null)
                    styleSheets.Add(sheet);
            }
        }

#if UNITY_EDITOR || DEVELOPMENT_BUILD || SUS_RUNTIME_MCP
        /// <summary>
        /// Reload companion stylesheets (.g.uss, _scoped.g.uss, _static.g.uss)
        /// without recreating the component. Used by UssHotReloadService for hot reload.
        /// Removes old companion sheets, loads new ones, and forces a redraw.
        /// <paramref name="onlySuffixes"/> — limit reload to specific
        /// suffixes ("_static.g" / "_scoped.g" / ".g"); null = all.
        /// </summary>
        public void ReloadCompanionStyleSheets(System.Collections.Generic.ICollection<string> onlySuffixes = null)
        {
            RemoveCompanionStyleSheets(onlySuffixes);

            // Reload from Resources / Editor fallback
            LoadCompanionStyleSheets(onlySuffixes);

            // Force UI Toolkit to re-resolve styles
            MarkDirtyRepaint();
        }

        /// <summary>
        /// Remove companion sheets without reloading (source deleted — stale styles).
        /// Keeps the global cascade (theme, tokens, reset, etc.) intact.
        /// </summary>
        public void RemoveCompanionStyleSheets(System.Collections.Generic.ICollection<string> onlySuffixes = null)
        {
            var className = GetType().Name;

            for (int i = styleSheets.count - 1; i >= 0; i--)
            {
                var sheet = styleSheets[i];
                if (sheet == null) continue;

                var sheetName = sheet.name;
                if (sheetName == null || !sheetName.Contains(className) || !sheetName.Contains(".g"))
                    continue;

                if (onlySuffixes != null)
                {
                    var match = false;
                    foreach (var suf in onlySuffixes)
                        if (sheetName == $"{className}{suf}") { match = true; break; }
                    if (!match) continue;
                }

                styleSheets.Remove(sheet);
            }
        }

        /// <summary>
        /// Hot-reload: replace companion sheet for <paramref name="suffix"/> with an in-memory
        /// <see cref="StyleSheet"/> (from USS text). Used by <c>SusRuntimeHotReload.ApplyUss</c>.
        /// </summary>
        public void ApplyHotReloadStyleSheet(string suffix, StyleSheet sheet)
        {
            if (sheet == null || string.IsNullOrEmpty(suffix)) return;
            var className = GetType().Name;
            var expectedName = $"{className}{suffix}";
            sheet.name = expectedName;

            for (int i = styleSheets.count - 1; i >= 0; i--)
            {
                var existing = styleSheets[i];
                if (existing != null && existing.name == expectedName)
                    styleSheets.Remove(existing);
            }

            styleSheets.Add(sheet);
            MarkDirtyRepaint();
        }
#endif

        // ─── Constructor ──────────────────────────────────────────────────

#if UNITY_EDITOR || DEVELOPMENT_BUILD
        private string _clickAuditDescription;
        private double _lastClickTime;
        private int _remountCount;
        private double _remountWindowStart;
        private int _layoutReentryCount;
        private double _layoutReentryWindow;
        private bool _layoutReentryWarnedThisWindow;
#endif

        protected SusComponent()
        {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
            DevConsole.ShouldTrace(GetType(), "Created", "");
#endif
            Created();
            BeforeMounted();
            Build();
            LoadCompanionStyleSheets();
            SusLabelClassService.InstallHooksRecursive(this);

#if UNITY_EDITOR || DEVELOPMENT_BUILD
            // Auto-register for click audit if description was set in Build()
            if (!string.IsNullOrEmpty(_clickAuditDescription))
                Diagnostics.ClickAuditService.Instance.Register(this, _clickAuditDescription);

            // Deferred bounds audit — check that element has non-zero size after layout
            schedule.Execute(() =>
            {
                if (panel == null) return;
                var wb = worldBound;
                if (wb.width <= 0 || wb.height <= 0)
                {
                    // Decorative (Ignore) or collapsed (display:none self/ancestor) — not a hit-target bug.
                    if (pickingMode == PickingMode.Ignore) return;
                    if (resolvedStyle.display == DisplayStyle.None) return;
                    for (var p = parent; p != null; p = p.parent)
                    {
                        if (p.resolvedStyle.display == DisplayStyle.None)
                            return;
                    }
                    UnityEngine.Debug.LogWarning($"[BoundsAudit] '{GetType().Name}' has zero bounds after mount " +
                        $"({wb.width:F0}×{wb.height:F0}). display={resolvedStyle.display}, " +
                        $"visible={visible}, pickingMode={pickingMode}. " +
                        $"Clicks will NOT reach this element.");
                }

                // ClickTargetSizeAudit: for interactive elements, check minimum tap target
                if (!string.IsNullOrEmpty(_clickAuditDescription))
                {
                    if (wb.width > 0 && wb.height > 0 && (wb.width < 30 || wb.height < 30))
                        UnityEngine.Debug.LogWarning($"[ClickTargetAudit] '{_clickAuditDescription}' " +
                            $"tap target is small ({wb.width:F0}×{wb.height:F0}px). " +
                            $"HIG recommends ≥44×44. Consider padding or min-size.");
                }
            }).StartingIn(150); // 2-3 frames for layout

            // PerformanceAudit — warn if element tree is too deep / too many children
            schedule.Execute(() =>
            {
                if (panel == null) return;
                var count = this.Query<VisualElement>().Build().ToList().Count;
                if (count > 500)
                    UnityEngine.Debug.LogWarning($"[PerfAudit] '{GetType().Name}' has {count} VisualElements. " +
                        $"Consider virtualization (SusTable) or paging.");
            }).StartingIn(500);

            // DebounceAudit — warns about double-clicks (<300ms) on any interactive element
            // Registered in the constructor → fires BEFORE handlers in Created() (UITK order is guaranteed)
            this.RegisterCallback<ClickEvent>(_ =>
            {
                if (string.IsNullOrEmpty(_clickAuditDescription)) return;
                var now = UnityEngine.Time.realtimeSinceStartupAsDouble;
                var elapsed = (now - _lastClickTime) * 1000.0;
                _lastClickTime = now;
                if (elapsed < 300.0 && elapsed >= 0)
                    UnityEngine.Debug.LogWarning($"[DebounceAudit] '{_clickAuditDescription}' " +
                        $"rapid double-click ({elapsed:F0}ms). Possible unintended double-submit.");
            });

            // IdleGuardAudit — warn if interactive element is visible but never clicked
            if (!string.IsNullOrEmpty(_clickAuditDescription))
            {
                schedule.Execute(() =>
                {
                    if (panel == null || !visible || resolvedStyle.display == DisplayStyle.None) return;
                    if (_lastClickTime == 0)
                        UnityEngine.Debug.LogWarning($"[IdleGuardAudit] '{_clickAuditDescription}' " +
                            $"visible but never clicked. " +
                            $"pickingMode={pickingMode}, worldBound=({worldBound.x:F0},{worldBound.y:F0} " +
                            $"{worldBound.width:F0}×{worldBound.height:F0}).");
                }).StartingIn(30000);
            }

            // OverflowAudit — check if any child exceeds parent bounds (Unity doesn't clip!)
            schedule.Execute(() =>
            {
                if (panel == null) return;
                var parentBounds = worldBound;
                if (parentBounds.width <= 0 || parentBounds.height <= 0) return;

                var overflowCount = 0;
                this.Query<VisualElement>().ForEach(child =>
                {
                    if (child == this) return;
                    var cb = child.worldBound;
                    if (cb.xMax > parentBounds.xMax + 2 || cb.yMax > parentBounds.yMax + 2 ||
                        cb.xMin < parentBounds.xMin - 2 || cb.yMin < parentBounds.yMin - 2)
                        overflowCount++;
                });
                if (overflowCount > 0)
                    UnityEngine.Debug.LogWarning($"[OverflowAudit] '{GetType().Name}' has " +
                        $"{overflowCount} child(ren) exceeding parent bounds " +
                        $"({parentBounds.width:F0}×{parentBounds.height:F0}). " +
                        $"Unity UITK does NOT clip overflow (no overflow:hidden).");
            }).StartingIn(200);
#endif

            // Defer Mounted to next frame so child elements are fully attached
            schedule.Execute(() =>
            {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
                DevConsole.ShouldTrace(GetType(), "Mounted", "");
#endif
                Mounted();
            }).StartingIn(0);

            // Register attach/detach callbacks
            RegisterCallback<AttachToPanelEvent>(OnAttachToPanelHandler);
            RegisterCallback<DetachFromPanelEvent>(OnDetachFromPanelHandler);
        }

        // ─── Reactive update scheduling ───────────────────────────────────

        private IVisualElementScheduledItem _updateItem;

        private void ScheduleReactiveUpdates()
        {
            _updateItem?.Pause();
            _updateItem = schedule.Execute(() =>
            {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
                DevConsole.ShouldTrace(GetType(), "Updated", "");
#endif
                Updated();
            });
            _updateItem.Every(16); // ~60 FPS
        }

        #region AttachToPanel / DetachFromPanel callbacks

        private void OnAttachToPanelHandler(AttachToPanelEvent evt)
        {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
            // RemountLoopAudit: detect rapid attach/detach cycles (>5 in 1 second)
            var now = UnityEngine.Time.realtimeSinceStartupAsDouble;
            if (now - _remountWindowStart > 1.0)
            {
                _remountCount = 0;
                _remountWindowStart = now;
            }
            _remountCount++;
            if (_remountCount > 5)
            {
                // F3.4: escalate to Error so STRICT OnLog → BattleFailFast CreationFlood
                UnityEngine.Debug.LogError($"[RemountLoopAudit] '{GetType().Name}' " +
                    $"attached {_remountCount} times in 1s. Possible Reactivity loop " +
                    $"(WatchEffect modifying visibility/layout).");
            }
#endif

            ScheduleReactiveUpdates();

            // Wire breakpoint service to geometry changes
            BreakpointService?.UpdateFromElement(this);
            RegisterCallback<GeometryChangedEvent>(OnGeometryChangedForBreakpoint);
        }

        private void OnGeometryChangedForBreakpoint(GeometryChangedEvent evt)
        {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
            var now = UnityEngine.Time.realtimeSinceStartupAsDouble;
            if (now - _layoutReentryWindow > 0.5)
            {
                _layoutReentryCount = 0;
                _layoutReentryWindow = now;
                _layoutReentryWarnedThisWindow = false;
            }
            _layoutReentryCount++;
            // Once per 500ms window — continuous warn flooded battle logs (GAP-20260729-001 T09).
            if (_layoutReentryCount > 20 && !_layoutReentryWarnedThisWindow)
            {
                _layoutReentryWarnedThisWindow = true;
                UnityEngine.Debug.LogWarning($"[LayoutReentryAudit] '{GetType().Name}' " +
                    $"{_layoutReentryCount}+ geometry changes in 500ms. " +
                    $"Possible layout loop — WatchEffect modifying size/position.");
            }
#endif

            BreakpointService?.UpdateFromElement(this);

            // Same path as deleted SusResolutionService: push cascade-root width
            // explicitly so .breakpoint-* stays on the token root even if the
            // per-component service lookup is still warming up.
            var cascadeRoot = SusBootstrap.TokenCascadeRoot
                ?? SusThemeService.ResolveCascadeRoot(this);
            if (cascadeRoot != null && cascadeRoot.panel != null)
            {
                var w = cascadeRoot.resolvedStyle.width;
                if (float.IsNaN(w) || w <= 0f)
                    w = cascadeRoot.layout.width;
                if (!float.IsNaN(w) && w > 0f)
                    SusBreakpointService.Attach(cascadeRoot).Update(w);
            }
        }

        private void OnDetachFromPanelHandler(DetachFromPanelEvent evt)
        {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
            var bindCount = _bindings.Count;
#endif
#if UNITY_EDITOR || DEVELOPMENT_BUILD
            DevConsole.ShouldTrace(GetType(), "BeforeUnmounted", "");
#endif
            BeforeUnmounted();
            _updateItem?.Pause();
            DisposeAllBindings();
            UnregisterCallback<GeometryChangedEvent>(OnGeometryChangedForBreakpoint);
#if UNITY_EDITOR || DEVELOPMENT_BUILD
            DevConsole.ShouldTrace(GetType(), "Unmounted", "");
#endif
            Unmounted();

#if UNITY_EDITOR || DEVELOPMENT_BUILD
            // LifecycleAudit: check for leaked bindings after detach
            if (bindCount > 0)
            {
                schedule.Execute(() =>
                {
                    if (panel == null && _bindings.Count > 0)
                        UnityEngine.Debug.LogWarning($"[LifecycleAudit] '{GetType().Name}' detached " +
                            $"with {_bindings.Count} leaked bindings (had {bindCount} before detach).");
                }).StartingIn(1000);
            }
#endif
        }

        /// <summary>
        /// Sets a property or field by name (case-insensitive) on a VisualElement child.
        /// Used by the Sharq compiler for prop passing: &lt;sus:Child variant="primary" /&gt;
        /// and &lt;sus:Child :variant="SourceProp" /&gt;.
        ///
        /// For Prop&lt;T&gt; fields: mutates .Value without replacing the instance
        /// (preserves internal bindings subscribed to the Prop).
        /// For plain types: direct property/field assignment.
        /// </summary>
        public static void SetChildProp(VisualElement child, string propName, object value)
        {
            if (child == null || string.IsNullOrEmpty(propName)) return;

            // Auto-unwrap Prop<T> → T.
            // When generator emits () => SomeProp (where SomeProp is Prop<int>),
            // the getter returns the Prop wrapper, not the inner value.
            if (value != null && IsPropType(value.GetType()))
            {
                var vp = value.GetType().GetProperty("Value");
                if (vp != null)
                    value = vp.GetValue(value);
            }

            var type = child.GetType();
            var flags = System.Reflection.BindingFlags.Public
                      | System.Reflection.BindingFlags.NonPublic
                      | System.Reflection.BindingFlags.Instance
                      | System.Reflection.BindingFlags.IgnoreCase;

            // Try field first
            var field = type.GetField(propName, flags);
            if (field != null)
            {
                var fieldValue = field.GetValue(child);
                if (fieldValue != null && IsPropType(field.FieldType))
                {
                    // Prop<T> — mutate .Value
                    var propValueField = field.FieldType.GetProperty("Value");
                    if (propValueField != null)
                    {
                        var converted = ConvertValue(value, propValueField.PropertyType);
                        propValueField.SetValue(fieldValue, converted);
                        return;
                    }
                }

                // Plain field — direct assignment
                var convertedField = ConvertValue(value, field.FieldType);
                field.SetValue(child, convertedField);
                return;
            }

            // Fallback to property
            var prop = type.GetProperty(propName, flags);
            if (prop != null && prop.CanWrite)
            {
                var propValue = prop.GetValue(child);
                if (propValue != null && IsPropType(prop.PropertyType))
                {
                    var innerValue = prop.PropertyType.GetProperty("Value");
                    if (innerValue != null)
                    {
                        var converted = ConvertValue(value, innerValue.PropertyType);
                        innerValue.SetValue(propValue, converted);
                        return;
                    }
                }

                var convertedProp = ConvertValue(value, prop.PropertyType);
                prop.SetValue(child, convertedProp);
            }
        }

        /// <summary>
        /// Reactive version of SetChildProp. Sets a child property immediately, then
        /// auto-updates whenever reactive sources read inside <paramref name="getter"/> change.
        /// Generated by the Sharq compiler for :prop="expr" bindings on custom components.
        /// </summary>
        protected void BindChildProp(VisualElement child, string propName, Func<object> getter)
        {
            if (child == null || string.IsNullOrEmpty(propName) || getter == null) return;

            // Initial set
            SetChildProp(child, propName, getter());

            // Reactive tracking — re-apply whenever any Prop/Computed read in getter changes
            WatchEffect(() =>
            {
                SetChildProp(child, propName, getter());
            });
        }

        private static bool IsPropType(Type type)
        {
            return type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Prop<>);
        }

        private static object ConvertValue(object value, Type targetType)
        {
            if (value == null) return targetType.IsValueType ? Activator.CreateInstance(targetType) : null;
            if (targetType.IsInstanceOfType(value)) return value;

            if (targetType == typeof(bool) && value is string s)
                return bool.TryParse(s, out var b) && b;

            if (targetType == typeof(string))
                return value.ToString();

            if (targetType.IsEnum && value is string es)
                return Enum.Parse(targetType, es, ignoreCase: true);

            try { return Convert.ChangeType(value, targetType); }
            catch { return value; }
        }

        #endregion

        // ─── v-for / BindListFor ────────────────────────────────────────

        /// <summary>
        /// Reactive list binding for v-for. Handles both IEnumerable&lt;T&gt;
        /// and Prop&lt;List&lt;T&gt;&gt; via reflection-based unwrapping.
        /// </summary>
        protected void BindListFor<T>(VisualElement container, object source,
            Func<T, int, VisualElement> factory, Func<T, object> keySelector = null)
        {
            if (container == null || factory == null) return;
            container.Clear();
            if (source == null) return;

            // Unwrap Prop<List<T>> or Prop<IEnumerable<T>>
            var sourceType = source.GetType();
            if (sourceType.IsGenericType && sourceType.GetGenericTypeDefinition() == typeof(Prop<>))
            {
                var valueProp = sourceType.GetProperty("Value");
                if (valueProp != null)
                    source = valueProp.GetValue(source);
            }

            if (source is IEnumerable<T> items)
            {
                int i = 0;
                foreach (var item in items)
                {
                    var child = factory(item, i);
                    if (child != null) container.Add(child);
                    i++;
                }
            }
        }

        /// <summary>
        /// Non-generic fallback for v-for without inferred item type.
        /// </summary>
        protected void BindListFor(VisualElement container, object source,
            Func<object, int, VisualElement> factory, Func<object, object> keySelector = null)
        {
            if (container == null || factory == null) return;
            container.Clear();
            if (source == null) return;

            // Unwrap Prop<List<T>> via reflection
            var sourceType = source.GetType();
            if (sourceType.IsGenericType && sourceType.GetGenericTypeDefinition() == typeof(Prop<>))
            {
                var valueProp = sourceType.GetProperty("Value");
                if (valueProp != null)
                    source = valueProp.GetValue(source);
            }

            if (source is System.Collections.IEnumerable items)
            {
                int i = 0;
                foreach (var item in items)
                {
                    var child = factory(item, i);
                    if (child != null) container.Add(child);
                    i++;
                }
            }
        }
    }
}
