using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UIElements;

namespace Sharq.Core
{
    /// <summary>
    /// Controls when WatchEffect callbacks are executed relative to Unity UI Toolkit layout.
    /// </summary>
    public enum FlushMode
    {
        /// <summary>Runs immediately on prop change, batched once per frame. Default.</summary>
        PreLayout = 0,

        /// <summary>Defers execution until after UI Toolkit layout pass.
        /// Use when the effect reads worldBound / resolvedStyle.</summary>
        PostLayout = 1,
    }

    /// <summary>
    /// Base class for all Sharq UI components. Extends Unity's VisualElement with
    /// Vue-like reactivity, lifecycle hooks, event system, slots, and bind helpers.
    ///
    /// The Build() method is generated by the Sharq Source Generator from .sharq files.
    /// </summary>
    public abstract partial class SusComponent : VisualElement
    {
        // ─── Reactivity helpers ───────────────────────────────────────────

        /// <summary>Create a reactive property.</summary>
        protected Prop<T> P<T>(T initial = default) => new(initial);

        /// <summary>Create a computed (derived) property.</summary>
        protected Computed<T> C<T>(Func<T> fn) => new(fn);

        /// <summary>
        /// Watch a Prop for changes. Returns an IDisposable handle;
        /// disposing it unsubscribes the watcher.
        /// </summary>
        protected WatchHandle Watch<T>(Prop<T> source, Action<T, T> callback)
        {
            if (source == null) throw new ArgumentNullException(nameof(source));
            if (callback == null) throw new ArgumentNullException(nameof(callback));

            source.Changed += callback;
            var h = new WatchHandle(() => source.Changed -= callback);
            TrackBinding(h);
            return h;
        }

        /// <summary>
        /// Watch a Prop for changes, registering the handle in an EffectScope.
        /// The scope owns the handle — calling scope.Dispose() unsubscribes.
        /// </summary>
        protected WatchHandle Watch<T>(Prop<T> source, Action<T, T> callback, EffectScope scope)
        {
            if (scope == null) throw new ArgumentNullException(nameof(scope));
            var h = Watch(source, callback);
            scope.Register(h);
            return h;
        }

        /// <summary>
        /// Create an EffectScope for grouping subscriptions.
        /// Analogous to Vue's effectScope(). Disposing the scope unsubscribes
        /// all watches registered through Watch(prop, cb, scope).
        /// </summary>
        protected EffectScope CreateScope() => new();

        /// <summary>
        /// Shared reactive primitive. Runs fn inside DependencyTracker.Track,
        /// subscribes to all reactive sources (Prop/Computed) read in fn,
        /// and re-runs fn on any invalidation via batched ScheduleBindUpdate.
        /// This is the single source of truth for all reactivity in sus-core.
        /// </summary>
        private WatchHandle ReactiveEffect(Action fn)
        {
            var subs = new System.Collections.Generic.List<IDisposable>();

            void Run()
            {
                foreach (var s in subs) s.Dispose();
                subs.Clear();

                using (DependencyTracker.Track(src =>
                    subs.Add(src.SubscribeInvalidate(() => ScheduleBindUpdate(Run)))))
                {
                    fn();
                }
            }

            Run();
            return new WatchHandle(() =>
            {
                foreach (var s in subs) s.Dispose();
                subs.Clear();
            });
        }

        /// <summary>
        /// Auto-tracking effect. Runs fn immediately, then auto-reruns when any Prop&lt;T&gt;
        /// or Computed&lt;T&gt; read inside fn changes. Equivalent to Vue's watchEffect().
        ///
        /// Example:
        /// <code>
        /// WatchEffect(() => {
        ///     var hp = Health.Value;
        ///     var max = MaxHealth.Value;
        ///     label.text = $"{hp}/{max}";
        /// });
        /// </code>
        /// </summary>
        protected WatchHandle WatchEffect(Action fn)
        {
            if (fn == null) throw new ArgumentNullException(nameof(fn));
            var h = ReactiveEffect(fn);
            TrackBinding(h);
            return h;
        }

        /// <summary>
        /// Auto-tracking effect with flush mode.
        ///
        /// <list type="bullet">
        /// <item><b>PreLayout</b> (default): runs immediately on prop change,
        ///   batched once per frame. Use for data mutations, text updates.</item>
        /// <item><b>PostLayout</b>: defers execution until after Unity UI Toolkit
        ///   completes its layout pass. Use when fn reads worldBound / resolvedStyle.</item>
        /// </list>
        ///
        /// Analogous to Vue watchPostEffect() / React useLayoutEffect.
        /// <code>
        /// WatchEffect(() => {
        ///     PositionSlider(_slider.worldBound.width);
        /// }, FlushMode.PostLayout);
        /// </code>
        /// </summary>
        protected WatchHandle WatchEffect(Action fn, FlushMode flush)
        {
            if (fn == null) throw new ArgumentNullException(nameof(fn));

            if (flush == FlushMode.PostLayout)
            {
                var h = ReactiveEffectPostLayout(fn);
                TrackBinding(h);
                return h;
            }

            return WatchEffect(fn);
        }

        private WatchHandle ReactiveEffectPostLayout(Action fn)
        {
            var subs = new System.Collections.Generic.List<IDisposable>();

            void Run()
            {
                foreach (var s in subs) s.Dispose();
                subs.Clear();

                using (DependencyTracker.Track(src =>
                    subs.Add(src.SubscribeInvalidate(() => ScheduleBindUpdate(Run)))))
                {
                    // Defer execution to after Unity UI Toolkit layout pass
                    schedule.Execute(fn).ExecuteLater(0);
                }
            }

            Run();
            return new WatchHandle(() =>
            {
                foreach (var s in subs) s.Dispose();
                subs.Clear();
            });
        }

        // ─── Binding lifecycle ────────────────────────────────────────────

        private readonly List<WatchHandle> _bindings = new();


        // ─── Breakpoint Service ───────────────────────────────────────────

        /// <summary>
        /// Reactive breakpoint service — tracks screen width and exposes
        /// IsMobile / IsTablet / IsDesktop computed properties.
        /// Lazy-initialized: first access gets or creates the shared
        /// per-root service via SusBreakpointService.For(this).
        /// </summary>
        public SusBreakpointService BreakpointService
        {
            get
            {
                if (_breakpointService == null)
                    _breakpointService = SusBreakpointService.For(this);
                return _breakpointService;
            }
            protected set => _breakpointService = value;
        }
        private SusBreakpointService _breakpointService;

        // Click audit API → SusComponent.Audits.cs

        // ─── Overlay convenience methods ──────────────────────────────────
        /// <summary>
        /// Adds an element to the nearest OverlayHost in the visual tree.
        /// Traverses up to root to find or create the overlay container
        /// (<see cref="SusBootstrap.ResolveOverlayHost"/> - ancestor-first, panel root as
        /// fallback, T-3032). Returns null when there is neither a host above this component
        /// nor a panel to create one in.
        /// </summary>
        protected OverlayEntry AddToOverlay(VisualElement element, OverlayCategory category,
            bool dismissOnClickOutside = false, System.Action onDismiss = null)
        {
            if (element == null) return null;

            var overlay = SusBootstrap.ResolveOverlayHost(this);
            if (overlay == null) return null;
            return overlay.AddToOverlay(element, category, dismissOnClickOutside, onDismiss);
        }

        /// <summary>
        /// Removes an element from the OverlayHost it actually sits in - the host that owns
        /// <paramref name="element"/>, not whichever host this component would resolve now
        /// (they differ once nearest-host resolution is in play, T-3032).
        /// </summary>
        protected void RemoveFromOverlay(VisualElement element)
        {
            if (element == null) return;

            var overlay = SusBootstrap.FindOverlayHost(element)
                          ?? SusBootstrap.FindOverlayHost(this);
            overlay?.RemoveFromOverlay(element);
        }

        // ─── Generated by Source Generator ────────────────────────────────

        /// <summary>
        /// Builds the visual tree. Implemented by the Source Generator
        /// in a partial class from .sharq &lt;template&gt; section.
        /// </summary>
        protected abstract void Build();

        // ─── Scoped CSS ───────────────────────────────────────────────────

        /// <summary>
        /// Applies a scoped CSS class to this element for isolation.
        /// Called by generated Build() when &lt;style scoped&gt; is present.
        /// </summary>
        protected void ApplyScopedAttribute(string hash)
        {
            AddToClassList(hash);
        }


        // ─── Product-surface marker ───────────────────────────────────────

        /// <summary>
        /// Class carried by EVERY SUS surface — each <see cref="SusComponent"/> and each
        /// <see cref="SusLayer"/> (card T-3416). It is the ANCHOR a package stylesheet uses
        /// when it has to dress Unity's own chrome (<c>.unity-button__label</c>,
        /// <c>.unity-text-field__input</c>, …): those classes are common ground — every
        /// <c>Button</c> and <c>Label</c> in the panel carries them, whoever built it — so an
        /// unanchored rule about them repaints the HOST's interface too, not only ours.
        ///
        /// Measured on the storybook shell 2026-09-11: 69 of 142 shell text elements sat on the
        /// product face and 107 colours moved with the product theme, none of it asked for
        /// (cards T-3357 / T-3400). The cure has to live where the rule lives, and a rule can
        /// only be anchored on something the markup actually carries — hence this class.
        ///
        /// Do NOT hang looks on it: it is a boundary, not a skin. Nothing in core styles it.
        /// </summary>
        public const string SurfaceClass = "sus-component";

        // ─── Constructor ──────────────────────────────────────────────────

        protected SusComponent()
        {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
            DevConsole.ShouldTrace(GetType(), "Created", "");
#endif
            // Before Build(): the generated tree is queried by class in tests and tooling, and a
            // surface that is not marked until after its children exist is a surface a descendant
            // rule can miss on the first layout pass.
            AddToClassList(SurfaceClass);

            Created();
            BeforeMounted();
            Build();
            LoadCompanionStyleSheets();
            SusLabelClassService.InstallHooksRecursive(this);

#if UNITY_EDITOR || DEVELOPMENT_BUILD
            RegisterDevAudits();
#endif

            // Defer Mounted to next frame so child elements are fully attached
            schedule.Execute(() =>
            {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
                DevConsole.ShouldTrace(GetType(), "Mounted", "");
#endif
                Mounted();
                IsMounted = true;
                var mounted = MountCompleted;
                MountCompleted = null;          // one-shot: nobody waits for a second mount
                mounted?.Invoke();
            }).StartingIn(0);

            // Register attach/detach callbacks
            RegisterCallback<AttachToPanelEvent>(OnAttachToPanelHandler);
            RegisterCallback<DetachFromPanelEvent>(OnDetachFromPanelHandler);
        }

        // ─── Reactive update scheduling ───────────────────────────────────

        private IVisualElementScheduledItem _updateItem;

        // Updated() is a no-op virtual by default (SusComponent.Lifecycle.cs). Scheduling
        // an Every(16) tick for it on EVERY component — most of which never override it — burns
        // 60Hz calls that do nothing. Cache per-type whether Updated() is actually overridden
        // anywhere in the hierarchy and skip scheduling entirely when it is not.
        private static readonly Dictionary<Type, bool> s_updatedOverrideCache = new Dictionary<Type, bool>();

        // internal (not private): SusComponentUpdateSchedulingTests verifies the
        // override-detection directly without needing a live panel attach/detach cycle.
        internal static bool TypeOverridesUpdated(Type type)
        {
            if (s_updatedOverrideCache.TryGetValue(type, out var cached))
                return cached;

            var method = type.GetMethod("Updated",
                System.Reflection.BindingFlags.Instance
                | System.Reflection.BindingFlags.Public
                | System.Reflection.BindingFlags.NonPublic);
            var overridden = method != null && method.DeclaringType != typeof(SusComponent);
            s_updatedOverrideCache[type] = overridden;
            return overridden;
        }

        private void ScheduleReactiveUpdates()
        {
            _updateItem?.Pause();
            _updateItem = null;

            if (!TypeOverridesUpdated(GetType())) return;

            _updateItem = schedule.Execute(() =>
            {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
                DevConsole.ShouldTrace(GetType(), "Updated", "");
#endif
                Updated();
            });
            _updateItem.Every(16); // ~60 FPS
        }

        #region AttachToPanel / DetachFromPanel callbacks

        private void OnAttachToPanelHandler(AttachToPanelEvent evt)
        {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
            RunRemountLoopAudit();
#endif

            ScheduleReactiveUpdates();

            // Prop invalidations before Add() queued actions but schedule was a no-op.
            FlushPendingBindUpdatesOnAttach();

            // Wire breakpoint service to geometry changes
            BreakpointService?.UpdateFromElement(this);
            RegisterCallback<GeometryChangedEvent>(OnGeometryChangedForBreakpoint);
        }

        private void OnGeometryChangedForBreakpoint(GeometryChangedEvent evt)
        {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
            RunLayoutReentryAudit();
#endif

            BreakpointService?.UpdateFromElement(this);

            // Same path as deleted SusResolutionService: push cascade-root width
            // explicitly so .breakpoint-* stays on the token root even if the
            // per-component service lookup is still warming up.
            var cascadeRoot = SusBootstrap.TokenCascadeRoot
                ?? SusThemeService.ResolveCascadeRoot(this);
            if (cascadeRoot != null && cascadeRoot.panel != null)
            {
                var w = cascadeRoot.resolvedStyle.width;
                if (float.IsNaN(w) || w <= 0f)
                    w = cascadeRoot.layout.width;
                if (!float.IsNaN(w) && w > 0f)
                    SusBreakpointService.Attach(cascadeRoot).Update(w);
            }
        }

        private void OnDetachFromPanelHandler(DetachFromPanelEvent evt)
        {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
            var bindCount = _bindings.Count;
#endif
#if UNITY_EDITOR || DEVELOPMENT_BUILD
            DevConsole.ShouldTrace(GetType(), "BeforeUnmounted", "");
#endif
            BeforeUnmounted();
            _updateItem?.Pause();
            // skip during a same-panel relocation (see IsRelocating) — this detach is not
            // a real unmount, and disposing bindings here would permanently kill Watch()/WatchEffect()
            // set up once in Created() (e.g. SusModal's Model watcher stops reacting after first open).
            if (!IsRelocating)
                DisposeAllBindings();
            _pendingBindActions.Clear();
            _bindScheduleItem = null;
            UnregisterCallback<GeometryChangedEvent>(OnGeometryChangedForBreakpoint);
#if UNITY_EDITOR || DEVELOPMENT_BUILD
            DevConsole.ShouldTrace(GetType(), "Unmounted", "");
#endif
            Unmounted();

#if UNITY_EDITOR || DEVELOPMENT_BUILD
            // LifecycleAudit: check for leaked bindings after detach
            if (bindCount > 0)
            {
                schedule.Execute(() =>
                {
                    if (panel == null && _bindings.Count > 0)
                        SusLog.Verbose($"[LifecycleAudit] '{GetType().Name}' detached " +
                            $"with {_bindings.Count} leaked bindings (had {bindCount} before detach).");
                }).StartingIn(1000);
            }
#endif
        }


        #endregion

        // ─── v-for / BindListFor ────────────────────────────────────────

        /// <summary>
        /// Reactive list binding for v-for. Handles both IEnumerable&lt;T&gt;
        /// and Prop&lt;List&lt;T&gt;&gt; via reflection-based unwrapping.
        /// </summary>
        protected void BindListFor<T>(VisualElement container, object source,
            Func<T, int, VisualElement> factory, Func<T, object> keySelector = null)
        {
            if (container == null || factory == null) return;
            container.Clear();
            if (source == null) return;

            // Unwrap Prop<List<T>> or Prop<IEnumerable<T>>
            var sourceType = source.GetType();
            if (sourceType.IsGenericType && sourceType.GetGenericTypeDefinition() == typeof(Prop<>))
            {
                var valueProp = sourceType.GetProperty("Value");
                if (valueProp != null)
                    source = valueProp.GetValue(source);
            }

            if (source is IEnumerable<T> items)
            {
                int i = 0;
                foreach (var item in items)
                {
                    var child = factory(item, i);
                    if (child != null) container.Add(child);
                    i++;
                }
            }
        }

        /// <summary>
        /// Non-generic fallback for v-for without inferred item type.
        /// </summary>
        protected void BindListFor(VisualElement container, object source,
            Func<object, int, VisualElement> factory, Func<object, object> keySelector = null)
        {
            if (container == null || factory == null) return;
            container.Clear();
            if (source == null) return;

            // Unwrap Prop<List<T>> via reflection
            var sourceType = source.GetType();
            if (sourceType.IsGenericType && sourceType.GetGenericTypeDefinition() == typeof(Prop<>))
            {
                var valueProp = sourceType.GetProperty("Value");
                if (valueProp != null)
                    source = valueProp.GetValue(source);
            }

            if (source is System.Collections.IEnumerable items)
            {
                int i = 0;
                foreach (var item in items)
                {
                    var child = factory(item, i);
                    if (child != null) container.Add(child);
                    i++;
                }
            }
        }
    }
}
