using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UIElements;

namespace Sharq.Core
{
    /// <summary>
    /// Controls when WatchEffect callbacks are executed relative to Unity UI Toolkit layout.
    /// </summary>
    public enum FlushMode
    {
        /// <summary>Runs immediately on prop change, batched once per frame. Default.</summary>
        PreLayout = 0,

        /// <summary>Defers execution until after UI Toolkit layout pass.
        /// Use when the effect reads worldBound / resolvedStyle.</summary>
        PostLayout = 1,
    }

    /// <summary>
    /// Base class for all Sharq UI components. Extends Unity's VisualElement with
    /// Vue-like reactivity, lifecycle hooks, event system, slots, and bind helpers.
    ///
    /// The Build() method is generated by the Sharq Source Generator from .sharq files.
    /// </summary>
    public abstract partial class SusComponent : VisualElement
    {
        // ─── Reactivity helpers ───────────────────────────────────────────

        /// <summary>Create a reactive property.</summary>
        protected Prop<T> P<T>(T initial = default) => new(initial);

        /// <summary>Create a computed (derived) property.</summary>
        protected Computed<T> C<T>(Func<T> fn) => new(fn);

        /// <summary>
        /// Watch a Prop for changes. Returns an IDisposable handle;
        /// disposing it unsubscribes the watcher.
        /// </summary>
        protected WatchHandle Watch<T>(Prop<T> source, Action<T, T> callback)
        {
            if (source == null) throw new ArgumentNullException(nameof(source));
            if (callback == null) throw new ArgumentNullException(nameof(callback));

            source.Changed += callback;
            var h = new WatchHandle(() => source.Changed -= callback);
            TrackBinding(h);
            return h;
        }

        /// <summary>
        /// Watch a Prop for changes, registering the handle in an EffectScope.
        /// The scope owns the handle — calling scope.Dispose() unsubscribes.
        /// </summary>
        protected WatchHandle Watch<T>(Prop<T> source, Action<T, T> callback, EffectScope scope)
        {
            if (scope == null) throw new ArgumentNullException(nameof(scope));
            var h = Watch(source, callback);
            scope.Register(h);
            return h;
        }

        /// <summary>
        /// Create an EffectScope for grouping subscriptions.
        /// Analogous to Vue's effectScope(). Disposing the scope unsubscribes
        /// all watches registered through Watch(prop, cb, scope).
        /// </summary>
        protected EffectScope CreateScope() => new();

        /// <summary>
        /// Shared reactive primitive. Runs fn inside DependencyTracker.Track,
        /// subscribes to all reactive sources (Prop/Computed) read in fn,
        /// and re-runs fn on any invalidation via batched ScheduleBindUpdate.
        /// This is the single source of truth for all reactivity in sus-core.
        /// </summary>
        private WatchHandle ReactiveEffect(Action fn)
        {
            var subs = new System.Collections.Generic.List<IDisposable>();

            void Run()
            {
                foreach (var s in subs) s.Dispose();
                subs.Clear();

                using (DependencyTracker.Track(src =>
                    subs.Add(src.SubscribeInvalidate(() => ScheduleBindUpdate(Run)))))
                {
                    fn();
                }
            }

            Run();
            return new WatchHandle(() =>
            {
                foreach (var s in subs) s.Dispose();
                subs.Clear();
            });
        }

        /// <summary>
        /// Auto-tracking effect. Runs fn immediately, then auto-reruns when any Prop&lt;T&gt;
        /// or Computed&lt;T&gt; read inside fn changes. Equivalent to Vue's watchEffect().
        ///
        /// Example:
        /// <code>
        /// WatchEffect(() => {
        ///     var hp = Health.Value;
        ///     var max = MaxHealth.Value;
        ///     label.text = $"{hp}/{max}";
        /// });
        /// </code>
        /// </summary>
        protected WatchHandle WatchEffect(Action fn)
        {
            if (fn == null) throw new ArgumentNullException(nameof(fn));
            var h = ReactiveEffect(fn);
            TrackBinding(h);
            return h;
        }

        /// <summary>
        /// Auto-tracking effect with flush mode.
        ///
        /// <list type="bullet">
        /// <item><b>PreLayout</b> (default): runs immediately on prop change,
        ///   batched once per frame. Use for data mutations, text updates.</item>
        /// <item><b>PostLayout</b>: defers execution until after Unity UI Toolkit
        ///   completes its layout pass. Use when fn reads worldBound / resolvedStyle.</item>
        /// </list>
        ///
        /// Analogous to Vue watchPostEffect() / React useLayoutEffect.
        /// <code>
        /// WatchEffect(() => {
        ///     PositionSlider(_slider.worldBound.width);
        /// }, FlushMode.PostLayout);
        /// </code>
        /// </summary>
        protected WatchHandle WatchEffect(Action fn, FlushMode flush)
        {
            if (fn == null) throw new ArgumentNullException(nameof(fn));

            if (flush == FlushMode.PostLayout)
            {
                var h = ReactiveEffectPostLayout(fn);
                TrackBinding(h);
                return h;
            }

            return WatchEffect(fn);
        }

        private WatchHandle ReactiveEffectPostLayout(Action fn)
        {
            var subs = new System.Collections.Generic.List<IDisposable>();

            void Run()
            {
                foreach (var s in subs) s.Dispose();
                subs.Clear();

                using (DependencyTracker.Track(src =>
                    subs.Add(src.SubscribeInvalidate(() => ScheduleBindUpdate(Run)))))
                {
                    // Defer execution to after Unity UI Toolkit layout pass
                    schedule.Execute(fn).ExecuteLater(0);
                }
            }

            Run();
            return new WatchHandle(() =>
            {
                foreach (var s in subs) s.Dispose();
                subs.Clear();
            });
        }

        // ─── Binding lifecycle ────────────────────────────────────────────

        private readonly List<WatchHandle> _bindings = new();

        // ─── Batched bind update scheduling ────────────────────────────────

        private readonly HashSet<Action> _pendingBindActions = new();
        private IVisualElementScheduledItem _bindScheduleItem;

        /// <summary>
        /// Batches a bind-update action to execute once per frame.
        /// De-duplicates: same Action is only queued once.
        /// </summary>
        /// <remarks>
        /// UITK <see cref="VisualElement.schedule"/> is a no-op until the element is
        /// attached to a panel. Actions are still queued in <see cref="_pendingBindActions"/>
        /// and flushed from <see cref="OnAttachToPanelHandler"/> so Prop changes during
        /// Build / SetChildProp before <c>parent.Add()</c> still reach Bind*.
        /// </remarks>
        private void ScheduleBindUpdate(Action apply)
        {
            _pendingBindActions.Add(apply);
            if (panel == null)
                return;
            _bindScheduleItem ??= schedule.Execute(ApplyAllBindUpdates);
            _bindScheduleItem.ExecuteLater(0);
        }

        /// <summary>Safety bound for the re-entrant drain loop below — see remarks.
        /// A real WatchEffect-writes-derived-Prop chain settles in 1-2 iterations; this only
        /// exists to turn an actual A-writes-B-writes-A cycle into a logged warning instead
        /// of an infinite loop.</summary>
        private const int MaxSteadyStateFlushIterations = 100;

        /// <remarks>
        /// (2026-08-20): this used to be a single snapshot-and-clear pass. That silently
        /// dropped updates in the STEADY-STATE case (same failure class fixed for the
        /// attach-time path, but that fix did not cover this one): when a bind action run
        /// from this loop synchronously writes a Prop that ANOTHER Bind*/WatchEffect on the SAME
        /// component reads — e.g. <c>Mounted()</c>'s <c>WatchEffect(ApplyVisual)</c> sets a
        /// derived <c>HpText</c> Prop that <c>Build()</c>'s <c>BindText(HpCounterLabel, () =&gt;
        /// HpText.Value)</c> reads — the write's <c>Prop.Value</c> setter synchronously invokes
        /// <see cref="ScheduleBindUpdate"/> for the BindText effect. We are INSIDE this very
        /// scheduled item's dispatch (<c>_bindScheduleItem</c>'s <c>Execute</c> callback is on
        /// the stack right now), so that nested call's <c>_bindScheduleItem.ExecuteLater(0)</c>
        /// is a reentrant re-arm of the SAME scheduled item while UITK's scheduler is mid-
        /// dispatch for it — and per Unity's scheduler silently drops that re-arm. The
        /// action lands (harmlessly) back in <c>_pendingBindActions</c> for "next time", but
        /// there never IS a next time: nothing else ever re-triggers that scheduled item again,
        /// so the bound Label.text is stuck one generation behind forever.
        ///
        /// Fix: loop here instead of doing one pass. Newly-queued actions (from a bind action's
        /// own synchronous side effects) are applied immediately, within the SAME dispatch, so
        /// we never depend on a reentrant re-arm succeeding. Bounded by
        /// <see cref="MaxSteadyStateFlushIterations"/> so an actual A-writes-B-writes-A Prop
        /// cycle logs a warning and yields instead of hanging. Regression:
        /// SteadyStateBindCascadeTests (WatchEffect writes a derived Prop that a same-instance
        /// BindText/BindClass reads — must re-render every generation, not just the first).
        /// </remarks>
        private void ApplyAllBindUpdates()
        {
            var iterations = 0;
            while (_pendingBindActions.Count > 0)
            {
                if (++iterations > MaxSteadyStateFlushIterations)
                {
                    SusLog.Warn(
                        $"[SusComponent] ApplyAllBindUpdates on {GetType().Name} exceeded " +
                        $"{MaxSteadyStateFlushIterations} re-entrant iterations in one flush — " +
                        "likely a bind/WatchEffect cycle (a Prop write re-triggers itself, " +
                        "directly or via another Prop, on the same component). Remaining " +
                        "actions deferred to the next tick.");
                    break;
                }

                // Snapshot and clear to allow re-registration during execution
                var actions = new List<Action>(_pendingBindActions);
                _pendingBindActions.Clear();
                foreach (var action in actions)
                    action();
            }
        }

        /// <summary>
        /// Catch up pending bind actions right on panel attach. Queued invalidations that
        /// arrived while detached never ran (schedule was a no-op — see <see cref="ScheduleBindUpdate"/>).
        /// </summary>
        /// <remarks>
        /// (2026-08-17): this used to defer the catch-up via
        /// <c>schedule.Execute(ApplyAllBindUpdates).ExecuteLater(0)</c>, i.e. it queued a NEW
        /// one-shot scheduled item on <c>this</c> element's panel scheduler instead of just
        /// running the pending actions directly. That is harmless for a single component
        /// attaching on its own — the one-shot item fires next tick and nothing else competes
        /// for it — but it silently dropped the flush when SEVERAL freshly-built reactive
        /// siblings attach in the SAME synchronous cascade (e.g. a list of rows built off-panel
        /// then added to an already-mounted host in one call — SusProfileScreenContent.SetFriends
        /// building N SusChip rows with Label/Color set before Add()). Every sibling's
        /// OnAttachToPanelHandler calls <c>schedule.Execute(...)</c> reentrantly on the SAME
        /// panel scheduler within the SAME editor tick while that scheduler is itself mid-dispatch
        /// for the ongoing attach; some of those one-shot items never got a chance to fire, so the
        /// affected sibling's BindClass/BindVisibility never applied — permanently, since nothing
        /// else was pending to retrigger it (confirmed live via Unity MCP: forcing the same Prop
        /// again on the broken chip minutes later did not self-heal it either, because
        /// re-triggering ALSO goes through <c>ScheduleBindUpdate</c> → the very same scheduler
        /// call that was already dropping items for that element). There is no reason for this
        /// specific catch-up to go through the scheduler at all: we are already inside the
        /// synchronous AttachToPanelEvent dispatch, so applying pending actions directly is both
        /// simpler and immune to sibling scheduler contention. Regression tests:
        /// PreAttachBindFlushTests.TwoSiblings_PlainHost_PropsSetBeforeAdd_BothApplyOnSharedAttachBatch
        /// / ThreeSiblings_SusComponentHost_PropsSetBeforeAdd_AllApplyOnSharedAttachBatch.
        /// </remarks>
        // ─── bounded re-entrant flush (trampoline) ──────────────────
        // A bind action applied by ApplyAllBindUpdates() can itself perform a structural
        // change (BindVisibility re-Insert, a WatchEffect that Add()s a freshly-built
        // child) that attaches MORE elements to an already-on-panel parent — and UITK
        // dispatches THAT attach synchronously, nested inside the very call we are in.
        // If that nested element ALSO has a pending flush (very common: freshly-built
        // reactive content, props set before Add — exactly the pattern), calling
        // ApplyAllBindUpdates() directly here would recurse the SAME small chain of
        // frames (OnAttachToPanelHandler → FlushPendingBindUpdatesOnAttach →
        // ApplyAllBindUpdates → action) once per nesting level. For a static handful of
        // levels that's invisible; for a screen whose reveal cascades several levels
        // deep in one synchronous mount (GameFlow app boot building the whole initial
        // route tree) it compounds into a deep, repeating call pattern — harmless on
        // Mono's generous Editor stack, but exactly the shape of the WebGL wasm
        // "RangeError: Maximum call stack size exceeded" from (small wasm stack,
        // interpreted invoke_iii/invoke_ii trampolines burn more stack per managed
        // frame than native Mono).
        //
        // Fix: cap re-entrant synchronous flushes to depth 1. Anything nested deeper
        // is queued instead of executed inline, and drained ITERATIVELY by the
        // outermost (depth-0) caller once its own ApplyAllBindUpdates() returns — so
        // the whole cascade still fully flushes within the SAME tick (nobody observes
        // an unflushed frame), but the C# call stack used by SUS's own flush machinery
        // stays O(1) regardless of how many levels re-enter, instead of O(depth).
        //
        // Deliberately NOT falling back to schedule.Execute(...).ExecuteLater(0) for the
        // deferred case — that is the exact mechanism removed (reentrant
        // registration on the panel's scheduler while it is mid-dispatch silently drops
        // some one-shot items). The queue below is plain, private, and drained by a
        // normal loop, so it carries none of that race.
        [ThreadStatic] private static int _flushDepth;
        [ThreadStatic] private static Queue<SusComponent> _deferredFlushQueue;
        private bool _flushQueuedPending;

#if UNITY_EDITOR || DEVELOPMENT_BUILD
        /// <summary>Test-only count of flushes that were re-entrant (would have added a
        /// stack frame on top of an in-progress flush and were queued instead). A deep
        /// synchronous reveal cascade drives this above 0 — proving the guard actually
        /// intercepted nesting, not just that nesting never happens to occur. Regression
        /// tests reset this to 0 and assert on it (see).</summary>
        internal static int DebugInterceptedReentrantFlushCount;
#endif

        private void FlushPendingBindUpdatesOnAttach()
        {
            if (_pendingBindActions.Count == 0) return;

            if (_flushDepth > 0)
            {
                // Re-entrant: some ancestor's bind action is still on the stack, mid-flush,
                // and just attached us as a side effect. Don't add another frame on top of
                // that chain — queue for the outermost caller to drain after it returns.
                if (!_flushQueuedPending)
                {
                    _flushQueuedPending = true;
                    (_deferredFlushQueue ??= new Queue<SusComponent>()).Enqueue(this);
#if UNITY_EDITOR || DEVELOPMENT_BUILD
                    DebugInterceptedReentrantFlushCount++;
#endif
                }
                return;
            }

            _flushDepth = 1;
            try
            {
                ApplyAllBindUpdates();
                DrainDeferredFlushQueue();
            }
            finally
            {
                _flushDepth = 0;
            }
        }

        private static void DrainDeferredFlushQueue()
        {
            var queue = _deferredFlushQueue;
            if (queue == null) return;
            while (queue.Count > 0)
            {
                var comp = queue.Dequeue();
                comp._flushQueuedPending = false;
                comp.ApplyAllBindUpdates();
            }
        }

        /// <summary>
        /// Creates a WatchHandle for manual subscription tracking.
        /// Use when you need to TrackBinding() for non-standard callbacks
        /// (e.g. Controller.Errors.Changed) that can't use Bind* methods.
        /// </summary>
        protected static WatchHandle CreateWatchHandle(Action unsubscribe)
        {
            return new WatchHandle(unsubscribe);
        }

        /// Registers a binding's WatchHandle so it can be disposed on detach.
        /// Called by all Bind* methods and Watch/WatchEffect.
        /// </summary>
        protected void TrackBinding(WatchHandle h)
        {
            if (h != null) _bindings.Add(h);
        }

        private void DisposeAllBindings()
        {
            for (int i = _bindings.Count - 1; i >= 0; i--)
                _bindings[i].Dispose();
            _bindings.Clear();
            _eventHandlers?.Clear();
        }

        /// <summary>
        /// True while a subclass is synchronously relocating this element to a different
        /// parent WITHIN THE SAME PANEL — e.g. <see cref="SusOverlayComponent.IsRelocatingToOverlay"/>
        /// during <c>MountSelfInOverlay</c>/<c>UnmountSelfFromOverlay</c>. That relocation's own
        /// <c>RemoveFromHierarchy()</c>/<c>Add()</c> calls trigger a REAL Attach/DetachFromPanelEvent
        /// as an implementation detail of UI Toolkit reparenting, even though the element never
        /// truly leaves the visual tree. <see cref="OnDetachFromPanelHandler"/> checks this to skip
        /// <see cref="DisposeAllBindings"/> during a pure reparent — without it, every
        /// <c>Watch()</c>/<c>WatchEffect()</c> registered in <c>Created()</c> (which runs once, in
        /// the constructor) gets permanently unsubscribed the first time an overlay-hosted component
        /// (Modal/Toast) opens, silently breaking all future reactivity to that Prop (e.g. SusModal's
        /// <c>Watch(Model,...)</c> never firing again after the first open).
        /// </summary>
        protected virtual bool IsRelocating => false;

        // ─── Breakpoint Service ───────────────────────────────────────────

        /// <summary>
        /// Reactive breakpoint service — tracks screen width and exposes
        /// IsMobile / IsTablet / IsDesktop computed properties.
        /// Lazy-initialized: first access gets or creates the shared
        /// per-root service via SusBreakpointService.For(this).
        /// </summary>
        public SusBreakpointService BreakpointService
        {
            get
            {
                if (_breakpointService == null)
                    _breakpointService = SusBreakpointService.For(this);
                return _breakpointService;
            }
            protected set => _breakpointService = value;
        }
        private SusBreakpointService _breakpointService;

        // Click audit API → SusComponent.Audits.cs

        // ─── Overlay convenience methods ──────────────────────────────────
        /// <summary>
        /// Adds an element to the nearest OverlayHost in the visual tree.
        /// Traverses up to root to find or create the overlay container.
        /// Returns null if no root panel is attached.
        /// </summary>
        protected OverlayEntry AddToOverlay(VisualElement element, OverlayCategory category,
            bool dismissOnClickOutside = false, System.Action onDismiss = null)
        {
            if (element == null) return null;
            if (panel == null) return null;

            var root = panel.visualTree;
            var overlay = SusBootstrap.GetOrCreateOverlay(root);
            return overlay.AddToOverlay(element, category, dismissOnClickOutside, onDismiss);
        }

        /// <summary>
        /// Removes an element from the nearest OverlayHost.
        /// </summary>
        protected void RemoveFromOverlay(VisualElement element)
        {
            if (element == null || panel == null) return;
            var root = panel.visualTree;
            if (root.childCount == 0) return;
            var last = root.ElementAt(root.childCount - 1);
            if (last is OverlayHost overlay)
                overlay.RemoveFromOverlay(element);
        }

        // ─── Generated by Source Generator ────────────────────────────────

        /// <summary>
        /// Builds the visual tree. Implemented by the Source Generator
        /// in a partial class from .sharq &lt;template&gt; section.
        /// </summary>
        protected abstract void Build();

        // ─── Scoped CSS ───────────────────────────────────────────────────

        /// <summary>
        /// Applies a scoped CSS class to this element for isolation.
        /// Called by generated Build() when &lt;style scoped&gt; is present.
        /// </summary>
        protected void ApplyScopedAttribute(string hash)
        {
            AddToClassList(hash);
        }

        // ─── USS Auto-loading ────────────────────────────────────────────

#if UNITY_EDITOR
        /// <summary>
        /// Editor-only development fallback dirs for companion USS resolution when the
        /// Resources copy is missing/stale. Defaults to the current project's Sharq output
        /// and sus-core's own Generated dir. Downstream packages register their own
        /// Generated dir via <see cref="RegisterEditorGeneratedDir"/> — core has
        /// no hardcoded knowledge of them.
        /// </summary>
        private static readonly System.Collections.Generic.List<string> s_editorGeneratedDirs = new()
        {
            "Assets/SusUI/Generated",                                 // project-local
            "Packages/com.sharq-it.sus.core/Runtime/Generated",      // core's own (self-reference OK)
        };

        /// <summary>
        /// Registers an editor-only fallback directory (AssetDatabase path, e.g.
        /// "Packages/com.example.ui/Runtime/Generated") for companion USS lookup.
        /// Idempotent. Editor-only — production builds resolve via Resources.
        /// </summary>
        public static void RegisterEditorGeneratedDir(string assetDir)
        {
            if (string.IsNullOrEmpty(assetDir)) return;
            if (!s_editorGeneratedDirs.Contains(assetDir))
                s_editorGeneratedDirs.Add(assetDir);
        }
#endif

        private static readonly string[] s_companionSuffixes = { "_static.g", "_scoped.g", ".g" };

        /// <summary>
        /// Caches, per most-derived component type, which type in its base-type chain actually
        /// owns the companion stylesheet(s) found on disk. A Tier-B C# subclass with no
        /// .sharq of its own (e.g. LfScoreboard : SusTable, LfNavButton : SusButton) has nothing
        /// under its OWN name — without this fallback its base's entire companion stylesheet
        /// silently never attaches. Caching avoids repeating the failing exact-name lookup (and
        /// the walk up the chain) on every construction of the same derived type — same pattern
        /// as <see cref="s_updatedOverrideCache"/> / prop-accessor cache.
        /// </summary>
        private static readonly Dictionary<Type, Type> s_companionOwnerTypeCache = new Dictionary<Type, Type>();

        /// <summary>
        /// Loads all companion USS files for this component from Resources/SusRuntime/.
        /// Tries: {ClassName}_static.g.uss, {ClassName}_scoped.g.uss, {ClassName}.g.uss
        /// Called automatically from generated Build().
        /// </summary>
        protected void LoadCompanionStyleSheets() => LoadCompanionStyleSheets(null);

        /// <summary>
        /// Loads companion USS, optionally restricted to specific suffixes
        /// ("_static.g" / "_scoped.g" / ".g") for partial hot reload.
        ///
        /// Resolves the companion filename from <c>GetType()</c> first (exact match — the common
        /// case, and unchanged behavior for any type that has its own companion sheet). When that
        /// yields nothing at all, walks up the base-type chain (stopping at <see cref="SusComponent"/>)
        /// so a Tier-B subclass with no .sharq of its own inherits its nearest styled ancestor's
        /// companion stylesheet(s) instead of silently getting none.
        /// </summary>
        private void LoadCompanionStyleSheets(ICollection<string> onlySuffixes)
        {
            var mostDerived = GetType();

            // Fast path for the full load (the hot path — every construction): reuse the owner
            // type resolved for a prior instance of the same class instead of re-walking.
            if (onlySuffixes == null && s_companionOwnerTypeCache.TryGetValue(mostDerived, out var cachedOwner))
            {
                LoadCompanionStyleSheetsForType(cachedOwner, onlySuffixes);
                return;
            }

            for (var type = mostDerived; type != null; type = type.BaseType)
            {
                var anyLoaded = LoadCompanionStyleSheetsForType(type, onlySuffixes);
                if (anyLoaded)
                {
                    if (onlySuffixes == null)
                        s_companionOwnerTypeCache[mostDerived] = type;
                    return;
                }
                if (type == typeof(SusComponent)) break; // reached root — nothing found anywhere
            }

            // Nothing found anywhere in the chain (a component that simply has no companion USS
            // at all — the common case for plain code-only components). Cache the type itself, NOT
            // the root ancestor: RemoveCompanionStyleSheets/ApplyHotReloadStyleSheet key off this
            // cached owner too, and must keep matching sheet names built from THIS type's own name
            // (e.g. hand-added sheets named "<mostDerived>_scoped.g" in hot-reload/tests) — caching
            // the root here would make removal look for "SusComponent_scoped.g" instead and silently
            // fail to match anything.
            if (onlySuffixes == null)
                s_companionOwnerTypeCache[mostDerived] = mostDerived;
        }

        /// <summary>Loads companion sheets named after <paramref name="type"/> specifically (no fallback).</summary>
        private bool LoadCompanionStyleSheetsForType(Type type, ICollection<string> onlySuffixes)
        {
            var name = type.Name;
            var anyLoaded = false;
            foreach (var suf in s_companionSuffixes)
            {
                if (onlySuffixes != null && !onlySuffixes.Contains(suf)) continue;
                var fileName = suf.Length > 0 ? $"{name}{suf}" : name;
                var sheet = UnityEngine.Resources.Load<StyleSheet>(SusBootstrap.ResourcePath + fileName);

#if UNITY_EDITOR
                // Development fallback: Resources is the primary path; when the copy is
                // missing/stale, scan the registered Generated dirs (project + packages).
                if (sheet == null)
                {
                    foreach (var dir in s_editorGeneratedDirs)
                    {
                        sheet = UnityEditor.AssetDatabase.LoadAssetAtPath<StyleSheet>($"{dir}/{fileName}.uss");
                        if (sheet != null) break;
                    }
                }
#endif

                if (sheet != null)
                {
                    styleSheets.Add(sheet);
                    anyLoaded = true;
                }
            }
            return anyLoaded;
        }

#if UNITY_EDITOR || DEVELOPMENT_BUILD || SUS_RUNTIME_MCP
        /// <summary>
        /// Reload companion stylesheets (.g.uss, _scoped.g.uss, _static.g.uss)
        /// without recreating the component. Used by UssHotReloadService for hot reload.
        /// Removes old companion sheets, loads new ones, and forces a redraw.
        /// <paramref name="onlySuffixes"/> — limit reload to specific
        /// suffixes ("_static.g" / "_scoped.g" / ".g"); null = all.
        /// </summary>
        public void ReloadCompanionStyleSheets(System.Collections.Generic.ICollection<string> onlySuffixes = null)
        {
            RemoveCompanionStyleSheets(onlySuffixes);

            // Reload from Resources / Editor fallback
            LoadCompanionStyleSheets(onlySuffixes);

            // Force UI Toolkit to re-resolve styles
            MarkDirtyRepaint();
        }

        /// <summary>
        /// Remove companion sheets without reloading (source deleted — stale styles).
        /// Keeps the global cascade (theme, tokens, reset, etc.) intact.
        /// </summary>
        public void RemoveCompanionStyleSheets(System.Collections.Generic.ICollection<string> onlySuffixes = null)
        {
            // Tier-B subclasses load companion sheets under an ANCESTOR type's name
            // (e.g. LfScoreboard loads "SusTable.g.uss"); remove by the resolved owner type so
            // hot-reload actually strips the sheets that were actually added, not zero of them.
            var mostDerived = GetType();
            var ownerType = s_companionOwnerTypeCache.TryGetValue(mostDerived, out var cached) ? cached : mostDerived;
            var className = ownerType.Name;

            for (int i = styleSheets.count - 1; i >= 0; i--)
            {
                var sheet = styleSheets[i];
                if (sheet == null) continue;

                var sheetName = sheet.name;
                if (sheetName == null || !sheetName.Contains(className) || !sheetName.Contains(".g"))
                    continue;

                if (onlySuffixes != null)
                {
                    var match = false;
                    foreach (var suf in onlySuffixes)
                        if (sheetName == $"{className}{suf}") { match = true; break; }
                    if (!match) continue;
                }

                styleSheets.Remove(sheet);
            }
        }

        /// <summary>
        /// Hot-reload: replace companion sheet for <paramref name="suffix"/> with an in-memory
        /// <see cref="StyleSheet"/> (from USS text). Used by <c>SusRuntimeHotReload.ApplyUss</c>.
        /// </summary>
        public void ApplyHotReloadStyleSheet(string suffix, StyleSheet sheet)
        {
            if (sheet == null || string.IsNullOrEmpty(suffix)) return;
            var className = GetType().Name;
            var expectedName = $"{className}{suffix}";
            sheet.name = expectedName;

            for (int i = styleSheets.count - 1; i >= 0; i--)
            {
                var existing = styleSheets[i];
                if (existing != null && existing.name == expectedName)
                    styleSheets.Remove(existing);
            }

            styleSheets.Add(sheet);
            MarkDirtyRepaint();
        }
#endif

        // ─── Constructor ──────────────────────────────────────────────────

        protected SusComponent()
        {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
            DevConsole.ShouldTrace(GetType(), "Created", "");
#endif
            Created();
            BeforeMounted();
            Build();
            LoadCompanionStyleSheets();
            SusLabelClassService.InstallHooksRecursive(this);

#if UNITY_EDITOR || DEVELOPMENT_BUILD
            RegisterDevAudits();
#endif

            // Defer Mounted to next frame so child elements are fully attached
            schedule.Execute(() =>
            {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
                DevConsole.ShouldTrace(GetType(), "Mounted", "");
#endif
                Mounted();
            }).StartingIn(0);

            // Register attach/detach callbacks
            RegisterCallback<AttachToPanelEvent>(OnAttachToPanelHandler);
            RegisterCallback<DetachFromPanelEvent>(OnDetachFromPanelHandler);
        }

        // ─── Reactive update scheduling ───────────────────────────────────

        private IVisualElementScheduledItem _updateItem;

        // Updated() is a no-op virtual by default (SusComponent.Lifecycle.cs). Scheduling
        // an Every(16) tick for it on EVERY component — most of which never override it — burns
        // 60Hz calls that do nothing. Cache per-type whether Updated() is actually overridden
        // anywhere in the hierarchy and skip scheduling entirely when it is not.
        private static readonly Dictionary<Type, bool> s_updatedOverrideCache = new Dictionary<Type, bool>();

        // internal (not private): SusComponentUpdateSchedulingTests verifies the
        // override-detection directly without needing a live panel attach/detach cycle.
        internal static bool TypeOverridesUpdated(Type type)
        {
            if (s_updatedOverrideCache.TryGetValue(type, out var cached))
                return cached;

            var method = type.GetMethod("Updated",
                System.Reflection.BindingFlags.Instance
                | System.Reflection.BindingFlags.Public
                | System.Reflection.BindingFlags.NonPublic);
            var overridden = method != null && method.DeclaringType != typeof(SusComponent);
            s_updatedOverrideCache[type] = overridden;
            return overridden;
        }

        private void ScheduleReactiveUpdates()
        {
            _updateItem?.Pause();
            _updateItem = null;

            if (!TypeOverridesUpdated(GetType())) return;

            _updateItem = schedule.Execute(() =>
            {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
                DevConsole.ShouldTrace(GetType(), "Updated", "");
#endif
                Updated();
            });
            _updateItem.Every(16); // ~60 FPS
        }

        #region AttachToPanel / DetachFromPanel callbacks

        private void OnAttachToPanelHandler(AttachToPanelEvent evt)
        {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
            RunRemountLoopAudit();
#endif

            ScheduleReactiveUpdates();

            // Prop invalidations before Add() queued actions but schedule was a no-op.
            FlushPendingBindUpdatesOnAttach();

            // Wire breakpoint service to geometry changes
            BreakpointService?.UpdateFromElement(this);
            RegisterCallback<GeometryChangedEvent>(OnGeometryChangedForBreakpoint);
        }

        private void OnGeometryChangedForBreakpoint(GeometryChangedEvent evt)
        {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
            RunLayoutReentryAudit();
#endif

            BreakpointService?.UpdateFromElement(this);

            // Same path as deleted SusResolutionService: push cascade-root width
            // explicitly so .breakpoint-* stays on the token root even if the
            // per-component service lookup is still warming up.
            var cascadeRoot = SusBootstrap.TokenCascadeRoot
                ?? SusThemeService.ResolveCascadeRoot(this);
            if (cascadeRoot != null && cascadeRoot.panel != null)
            {
                var w = cascadeRoot.resolvedStyle.width;
                if (float.IsNaN(w) || w <= 0f)
                    w = cascadeRoot.layout.width;
                if (!float.IsNaN(w) && w > 0f)
                    SusBreakpointService.Attach(cascadeRoot).Update(w);
            }
        }

        private void OnDetachFromPanelHandler(DetachFromPanelEvent evt)
        {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
            var bindCount = _bindings.Count;
#endif
#if UNITY_EDITOR || DEVELOPMENT_BUILD
            DevConsole.ShouldTrace(GetType(), "BeforeUnmounted", "");
#endif
            BeforeUnmounted();
            _updateItem?.Pause();
            // skip during a same-panel relocation (see IsRelocating) — this detach is not
            // a real unmount, and disposing bindings here would permanently kill Watch()/WatchEffect()
            // set up once in Created() (e.g. SusModal's Model watcher stops reacting after first open).
            if (!IsRelocating)
                DisposeAllBindings();
            _pendingBindActions.Clear();
            _bindScheduleItem = null;
            UnregisterCallback<GeometryChangedEvent>(OnGeometryChangedForBreakpoint);
#if UNITY_EDITOR || DEVELOPMENT_BUILD
            DevConsole.ShouldTrace(GetType(), "Unmounted", "");
#endif
            Unmounted();

#if UNITY_EDITOR || DEVELOPMENT_BUILD
            // LifecycleAudit: check for leaked bindings after detach
            if (bindCount > 0)
            {
                schedule.Execute(() =>
                {
                    if (panel == null && _bindings.Count > 0)
                        SusLog.Verbose($"[LifecycleAudit] '{GetType().Name}' detached " +
                            $"with {_bindings.Count} leaked bindings (had {bindCount} before detach).");
                }).StartingIn(1000);
            }
#endif
        }

        /// <summary>
        /// Cached descriptor for a (child type, prop name) pair resolved once by
        /// <see cref="SetChildProp"/> — avoids re-running <c>GetField</c>/<c>GetProperty</c>
        /// reflection lookups on every prop-bind change (R-A2/P0-2).
        /// </summary>
        private sealed class ChildPropAccessor
        {
            internal static readonly ChildPropAccessor NotFound = new ChildPropAccessor { Found = false };

            internal bool Found = true;
            internal System.Reflection.FieldInfo Field;
            internal System.Reflection.PropertyInfo Property;
            internal bool IsPropWrapper;
            internal System.Reflection.PropertyInfo InnerValueProperty; // Prop<T>.Value, only when IsPropWrapper
            internal Type InnerValueType;
        }

        // (child type) → (prop name, case-insensitive) → accessor. Built lazily, once per pair.
        private static readonly Dictionary<Type, Dictionary<string, ChildPropAccessor>> s_childPropCache =
            new Dictionary<Type, Dictionary<string, ChildPropAccessor>>();

        // Type → "Value" PropertyInfo of that Prop<T>-shaped type. Shared by the incoming-value
        // unwrap in SetChildProp and by ChildPropAccessor construction.
        private static readonly Dictionary<Type, System.Reflection.PropertyInfo> s_propValuePropertyCache =
            new Dictionary<Type, System.Reflection.PropertyInfo>();

        private static System.Reflection.PropertyInfo GetPropValueProperty(Type propWrapperType)
        {
            if (!s_propValuePropertyCache.TryGetValue(propWrapperType, out var pi))
            {
                pi = propWrapperType.GetProperty("Value");
                s_propValuePropertyCache[propWrapperType] = pi;
            }
            return pi;
        }

        private static ChildPropAccessor GetChildPropAccessor(Type childType, string propName)
        {
            if (!s_childPropCache.TryGetValue(childType, out var byName))
            {
                byName = new Dictionary<string, ChildPropAccessor>(StringComparer.OrdinalIgnoreCase);
                s_childPropCache[childType] = byName;
            }
            if (byName.TryGetValue(propName, out var accessor))
                return accessor;

            accessor = BuildChildPropAccessor(childType, propName);
            byName[propName] = accessor;
            return accessor;
        }

        private static ChildPropAccessor BuildChildPropAccessor(Type childType, string propName)
        {
            const System.Reflection.BindingFlags flags = System.Reflection.BindingFlags.Public
                | System.Reflection.BindingFlags.NonPublic
                | System.Reflection.BindingFlags.Instance
                | System.Reflection.BindingFlags.IgnoreCase;

            var field = childType.GetField(propName, flags);
            if (field != null)
            {
                var isWrapper = IsPropType(field.FieldType);
                System.Reflection.PropertyInfo innerProp = null;
                Type innerType = null;
                if (isWrapper)
                {
                    innerProp = GetPropValueProperty(field.FieldType);
                    innerType = innerProp?.PropertyType;
                    isWrapper = innerProp != null;
                }
                return new ChildPropAccessor
                {
                    Field = field,
                    IsPropWrapper = isWrapper,
                    InnerValueProperty = innerProp,
                    InnerValueType = innerType,
                };
            }

            var prop = childType.GetProperty(propName, flags);
            if (prop != null && prop.CanWrite)
            {
                var isWrapper = IsPropType(prop.PropertyType);
                System.Reflection.PropertyInfo innerProp = null;
                Type innerType = null;
                if (isWrapper)
                {
                    innerProp = GetPropValueProperty(prop.PropertyType);
                    innerType = innerProp?.PropertyType;
                    isWrapper = innerProp != null;
                }
                return new ChildPropAccessor
                {
                    Property = prop,
                    IsPropWrapper = isWrapper,
                    InnerValueProperty = innerProp,
                    InnerValueType = innerType,
                };
            }

            return ChildPropAccessor.NotFound;
        }

        /// <summary>
        /// Sets a property or field by name (case-insensitive) on a VisualElement child.
        /// Used by the Sharq compiler for prop passing: &lt;sus:Child variant="primary" /&gt;
        /// and &lt;sus:Child :variant="SourceProp" /&gt;.
        ///
        /// For Prop&lt;T&gt; fields: mutates .Value without replacing the instance
        /// (preserves internal bindings subscribed to the Prop).
        /// For plain types: direct property/field assignment.
        ///
        /// The (child type, propName) accessor is resolved via reflection once and cached
        /// — repeat calls (every reactive re-apply of a :prop bind) skip GetField/
        /// GetProperty entirely.
        /// </summary>
        public static void SetChildProp(VisualElement child, string propName, object value)
        {
            if (child == null || string.IsNullOrEmpty(propName)) return;

            // Auto-unwrap Prop<T> → T.
            // When generator emits () => SomeProp (where SomeProp is Prop<int>),
            // the getter returns the Prop wrapper, not the inner value.
            if (value != null && IsPropType(value.GetType()))
            {
                var vp = GetPropValueProperty(value.GetType());
                if (vp != null)
                    value = vp.GetValue(value);
            }

            var accessor = GetChildPropAccessor(child.GetType(), propName);
            if (!accessor.Found) return;

            if (accessor.Field != null)
            {
                var fieldValue = accessor.Field.GetValue(child);
                if (fieldValue != null && accessor.IsPropWrapper)
                {
                    // Prop<T> — mutate .Value
                    var converted = ConvertValue(value, accessor.InnerValueType);
                    accessor.InnerValueProperty.SetValue(fieldValue, converted);
                    return;
                }

                // Plain field — direct assignment
                var convertedField = ConvertValue(value, accessor.Field.FieldType);
                accessor.Field.SetValue(child, convertedField);
                return;
            }

            // Property path
            var propValue = accessor.Property.GetValue(child);
            if (propValue != null && accessor.IsPropWrapper)
            {
                var converted = ConvertValue(value, accessor.InnerValueType);
                accessor.InnerValueProperty.SetValue(propValue, converted);
                return;
            }

            var convertedProp = ConvertValue(value, accessor.Property.PropertyType);
            accessor.Property.SetValue(child, convertedProp);
        }

        /// <summary>
        /// Reactive version of SetChildProp. Sets a child property immediately, then
        /// auto-updates whenever reactive sources read inside <paramref name="getter"/> change.
        /// Generated by the Sharq compiler for :prop="expr" bindings on custom components.
        /// </summary>
        protected void BindChildProp(VisualElement child, string propName, Func<object> getter)
        {
            if (child == null || string.IsNullOrEmpty(propName) || getter == null) return;

            // Initial set
            SetChildProp(child, propName, getter());

            // Reactive tracking — re-apply whenever any Prop/Computed read in getter changes
            WatchEffect(() =>
            {
                SetChildProp(child, propName, getter());
            });
        }

        private static bool IsPropType(Type type)
        {
            return type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Prop<>);
        }

        private static object ConvertValue(object value, Type targetType)
        {
            if (value == null) return targetType.IsValueType ? Activator.CreateInstance(targetType) : null;
            if (targetType.IsInstanceOfType(value)) return value;

            if (targetType == typeof(bool) && value is string s)
                return bool.TryParse(s, out var b) && b;

            if (targetType == typeof(string))
                return value.ToString();

            if (targetType.IsEnum && value is string es)
                return Enum.Parse(targetType, es, ignoreCase: true);

            try { return Convert.ChangeType(value, targetType); }
            catch { return value; }
        }

        #endregion

        // ─── v-for / BindListFor ────────────────────────────────────────

        /// <summary>
        /// Reactive list binding for v-for. Handles both IEnumerable&lt;T&gt;
        /// and Prop&lt;List&lt;T&gt;&gt; via reflection-based unwrapping.
        /// </summary>
        protected void BindListFor<T>(VisualElement container, object source,
            Func<T, int, VisualElement> factory, Func<T, object> keySelector = null)
        {
            if (container == null || factory == null) return;
            container.Clear();
            if (source == null) return;

            // Unwrap Prop<List<T>> or Prop<IEnumerable<T>>
            var sourceType = source.GetType();
            if (sourceType.IsGenericType && sourceType.GetGenericTypeDefinition() == typeof(Prop<>))
            {
                var valueProp = sourceType.GetProperty("Value");
                if (valueProp != null)
                    source = valueProp.GetValue(source);
            }

            if (source is IEnumerable<T> items)
            {
                int i = 0;
                foreach (var item in items)
                {
                    var child = factory(item, i);
                    if (child != null) container.Add(child);
                    i++;
                }
            }
        }

        /// <summary>
        /// Non-generic fallback for v-for without inferred item type.
        /// </summary>
        protected void BindListFor(VisualElement container, object source,
            Func<object, int, VisualElement> factory, Func<object, object> keySelector = null)
        {
            if (container == null || factory == null) return;
            container.Clear();
            if (source == null) return;

            // Unwrap Prop<List<T>> via reflection
            var sourceType = source.GetType();
            if (sourceType.IsGenericType && sourceType.GetGenericTypeDefinition() == typeof(Prop<>))
            {
                var valueProp = sourceType.GetProperty("Value");
                if (valueProp != null)
                    source = valueProp.GetValue(source);
            }

            if (source is System.Collections.IEnumerable items)
            {
                int i = 0;
                foreach (var item in items)
                {
                    var child = factory(item, i);
                    if (child != null) container.Add(child);
                    i++;
                }
            }
        }
    }
}
