using System;
using System.Collections.Generic;
using UnityEngine.UIElements;
using Sharq.Core;

// Auto-generated by SharqSourceGenerator from input.sharq
#nullable disable
[UxmlElement]
public partial class input : SusComponent
{
    // ─── From <script> ───
    public int X = 1;

    protected override void Build()
    {
        LoadCompanionStyleSheets();

        ApplyScopedAttribute("s-22fdba59");
        AddToClassList("box");
        var __el_0 = new Label();
        __el_0.text = "Hi";
        this.Add(__el_0);
    }

}
