using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace Sharq.Core.Editor.DesignImport
{
    /// <summary>
    /// Emit override USS (:root custom props + .breakpoint-* mode blocks).
    /// Compatible with SusBreakpointService class names. R22-clean — no web-only CSS.
    /// Does not patch shipped design-tokens.uss (ARCH-DESIGN-IMPORT D2).
    /// </summary>
    public static class UssEmitter
    {
        // Mirror RULES R22 denylist (subset relevant to generated custom-prop sheets)
        static readonly Regex Forbidden = new Regex(
            @"\b(z-index|box-shadow|gap|float)\b|position\s*:\s*(fixed|sticky)|overflow\s*:\s*(scroll|auto)|display\s*:\s*(grid|inline|block)|::(before|after)|@keyframes",
            RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

        static readonly HashSet<string> AllowedBreakpoints = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "breakpoint-sm", "breakpoint-md", "breakpoint-lg", "breakpoint-xl", "breakpoint-2xl"
        };

        public static string Emit(
            IEnumerable<MappedToken> mapped,
            IEnumerable<MappedModeBlock> modeBlocks = null,
            IList<string> r22Errors = null)
        {
            var list = DedupSorted(mapped);

            var sb = new StringBuilder();
            sb.AppendLine("/* Generated by SusDesignImport — override sheet. Do not edit design-tokens.uss. */");
            sb.AppendLine(":root {");
            AppendProps(sb, list);
            sb.AppendLine("}");
            sb.AppendLine();

            // Group by AppliesTo (stable sort of class names, then mode name for comments)
            var blocks = (modeBlocks ?? Enumerable.Empty<MappedModeBlock>())
                .Where(b => b != null
                            && !string.IsNullOrEmpty(b.AppliesTo)
                            && AllowedBreakpoints.Contains(b.AppliesTo)
                            && b.Tokens != null
                            && b.Tokens.Count > 0)
                .GroupBy(b => NormalizeBreakpointClass(b.AppliesTo), StringComparer.Ordinal)
                .OrderBy(g => BreakpointSortKey(g.Key))
                .ThenBy(g => g.Key, StringComparer.Ordinal)
                .ToList();

            foreach (var g in blocks)
            {
                // Merge tokens across modes that share the same appliesTo (last wins per css var)
                var merged = DedupSorted(g.SelectMany(b => b.Tokens));
                if (merged.Count == 0) continue;

                var modeNames = g.Select(b => b.ModeName)
                    .Where(n => !string.IsNullOrEmpty(n))
                    .Distinct(StringComparer.OrdinalIgnoreCase)
                    .OrderBy(n => n, StringComparer.Ordinal)
                    .ToList();
                if (modeNames.Count > 0)
                    sb.AppendLine($"/* mode(s): {string.Join(", ", modeNames)} → .{g.Key} (SusBreakpointService) */");

                sb.Append('.');
                sb.Append(g.Key);
                sb.AppendLine(" {");
                AppendProps(sb, merged);
                sb.AppendLine("}");
                sb.AppendLine();
            }

            var uss = sb.ToString();
            if (r22Errors != null)
            {
                foreach (Match hit in Forbidden.Matches(uss))
                    r22Errors.Add($"R22 forbidden construct in generated USS: '{hit.Value}'");
            }
            return uss;
        }

        /// <summary>Back-compat overload used by older call sites / CLI paths.</summary>
        public static string Emit(IEnumerable<MappedToken> mapped, IList<string> r22Errors) =>
            Emit(mapped, null, r22Errors);

        static void AppendProps(StringBuilder sb, List<MappedToken> list)
        {
            foreach (var m in list)
            {
                var value = NormalizeValue(m.Value);
                sb.Append("    ");
                sb.Append(m.CssVar);
                sb.Append(": ");
                sb.Append(value);
                sb.AppendLine(";");
            }
        }

        static List<MappedToken> DedupSorted(IEnumerable<MappedToken> mapped)
        {
            return (mapped ?? Enumerable.Empty<MappedToken>())
                .Where(m => m != null && !string.IsNullOrEmpty(m.CssVar))
                .GroupBy(m => m.CssVar, StringComparer.Ordinal)
                .Select(g => g.Last())
                .OrderBy(m => m.CssVar, StringComparer.Ordinal)
                .ToList();
        }

        static string NormalizeBreakpointClass(string appliesTo)
        {
            var s = (appliesTo ?? "").Trim().TrimStart('.');
            // Canonical lowercase with known spelling for 2xl
            if (s.Equals("breakpoint-2xl", StringComparison.OrdinalIgnoreCase))
                return "breakpoint-2xl";
            if (s.Equals("breakpoint-sm", StringComparison.OrdinalIgnoreCase)) return "breakpoint-sm";
            if (s.Equals("breakpoint-md", StringComparison.OrdinalIgnoreCase)) return "breakpoint-md";
            if (s.Equals("breakpoint-lg", StringComparison.OrdinalIgnoreCase)) return "breakpoint-lg";
            if (s.Equals("breakpoint-xl", StringComparison.OrdinalIgnoreCase)) return "breakpoint-xl";
            return s.ToLowerInvariant();
        }

        static int BreakpointSortKey(string cls) => cls switch
        {
            "breakpoint-sm" => 0,
            "breakpoint-md" => 1,
            "breakpoint-lg" => 2,
            "breakpoint-xl" => 3,
            "breakpoint-2xl" => 4,
            _ => 99
        };

        public static string NormalizeValue(string raw)
        {
            if (string.IsNullOrWhiteSpace(raw)) return "initial";
            var v = raw.Trim();

            // Hex color → rgb()/rgba() for UITK friendliness
            if (v.StartsWith("#", StringComparison.Ordinal))
            {
                if (TryParseHex(v, out var r, out var g, out var b, out var a))
                {
                    if (a < 255)
                    {
                        return string.Format(CultureInfo.InvariantCulture,
                            "rgba({0}, {1}, {2}, {3})", r, g, b,
                            Math.Round(a / 255.0, 4));
                    }
                    return string.Format(CultureInfo.InvariantCulture, "rgb({0}, {1}, {2})", r, g, b);
                }
            }

            // Bare number for dimension → px
            if (double.TryParse(v, NumberStyles.Float, CultureInfo.InvariantCulture, out _))
            {
                if (!v.EndsWith("px", StringComparison.OrdinalIgnoreCase) &&
                    !v.EndsWith("%", StringComparison.Ordinal) &&
                    !v.EndsWith("rem", StringComparison.OrdinalIgnoreCase) &&
                    !v.Contains("("))
                {
                    return v + "px";
                }
            }

            return v;
        }

        static bool TryParseHex(string hex, out int r, out int g, out int b, out int a)
        {
            r = g = b = 0;
            a = 255;
            var h = hex.TrimStart('#');
            if (h.Length == 3)
            {
                r = Convert.ToInt32(new string(h[0], 2), 16);
                g = Convert.ToInt32(new string(h[1], 2), 16);
                b = Convert.ToInt32(new string(h[2], 2), 16);
                return true;
            }
            if (h.Length == 6)
            {
                r = Convert.ToInt32(h.Substring(0, 2), 16);
                g = Convert.ToInt32(h.Substring(2, 2), 16);
                b = Convert.ToInt32(h.Substring(4, 2), 16);
                return true;
            }
            if (h.Length == 8)
            {
                r = Convert.ToInt32(h.Substring(0, 2), 16);
                g = Convert.ToInt32(h.Substring(2, 2), 16);
                b = Convert.ToInt32(h.Substring(4, 2), 16);
                a = Convert.ToInt32(h.Substring(6, 2), 16);
                return true;
            }
            return false;
        }
    }
}
