using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace Sharq.Core.Editor.DesignImport
{
    /// <summary>Emit override USS (:root custom props). R22-clean — no web-only CSS.</summary>
    public static class UssEmitter
    {
        // Mirror RULES R22 denylist (subset relevant to generated custom-prop sheets)
        static readonly Regex Forbidden = new Regex(
            @"\b(z-index|box-shadow|gap|float)\b|position\s*:\s*(fixed|sticky)|overflow\s*:\s*(scroll|auto)|display\s*:\s*(grid|inline|block)|::(before|after)|@keyframes",
            RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

        public static string Emit(IEnumerable<MappedToken> mapped, IList<string> r22Errors = null)
        {
            var list = mapped
                .Where(m => m != null && !string.IsNullOrEmpty(m.CssVar))
                .GroupBy(m => m.CssVar, StringComparer.Ordinal)
                .Select(g => g.Last())
                .OrderBy(m => m.CssVar, StringComparer.Ordinal)
                .ToList();

            var sb = new StringBuilder();
            sb.AppendLine("/* Generated by SusDesignImport — override sheet. Do not edit design-tokens.uss. */");
            sb.AppendLine(":root {");
            foreach (var m in list)
            {
                var value = NormalizeValue(m.Value);
                sb.Append("    ");
                sb.Append(m.CssVar);
                sb.Append(": ");
                sb.Append(value);
                sb.AppendLine(";");
            }
            sb.AppendLine("}");
            sb.AppendLine();

            var uss = sb.ToString();
            if (r22Errors != null)
            {
                foreach (Match hit in Forbidden.Matches(uss))
                    r22Errors.Add($"R22 forbidden construct in generated USS: '{hit.Value}'");
            }
            return uss;
        }

        public static string NormalizeValue(string raw)
        {
            if (string.IsNullOrWhiteSpace(raw)) return "initial";
            var v = raw.Trim();

            // Hex color → rgb()/rgba() for UITK friendliness
            if (v.StartsWith("#", StringComparison.Ordinal))
            {
                if (TryParseHex(v, out var r, out var g, out var b, out var a))
                {
                    if (a < 255)
                    {
                        return string.Format(CultureInfo.InvariantCulture,
                            "rgba({0}, {1}, {2}, {3})", r, g, b,
                            Math.Round(a / 255.0, 4));
                    }
                    return string.Format(CultureInfo.InvariantCulture, "rgb({0}, {1}, {2})", r, g, b);
                }
            }

            // Bare number for dimension → px
            if (double.TryParse(v, NumberStyles.Float, CultureInfo.InvariantCulture, out _))
            {
                if (!v.EndsWith("px", StringComparison.OrdinalIgnoreCase) &&
                    !v.EndsWith("%", StringComparison.Ordinal) &&
                    !v.EndsWith("rem", StringComparison.OrdinalIgnoreCase) &&
                    !v.Contains("("))
                {
                    return v + "px";
                }
            }

            return v;
        }

        static bool TryParseHex(string hex, out int r, out int g, out int b, out int a)
        {
            r = g = b = 0;
            a = 255;
            var h = hex.TrimStart('#');
            if (h.Length == 3)
            {
                r = Convert.ToInt32(new string(h[0], 2), 16);
                g = Convert.ToInt32(new string(h[1], 2), 16);
                b = Convert.ToInt32(new string(h[2], 2), 16);
                return true;
            }
            if (h.Length == 6)
            {
                r = Convert.ToInt32(h.Substring(0, 2), 16);
                g = Convert.ToInt32(h.Substring(2, 2), 16);
                b = Convert.ToInt32(h.Substring(4, 2), 16);
                return true;
            }
            if (h.Length == 8)
            {
                r = Convert.ToInt32(h.Substring(0, 2), 16);
                g = Convert.ToInt32(h.Substring(2, 2), 16);
                b = Convert.ToInt32(h.Substring(4, 2), 16);
                a = Convert.ToInt32(h.Substring(6, 2), 16);
                return true;
            }
            return false;
        }
    }
}
