using System.Text;

namespace Sharq.Bootstrap;

/// <summary>
/// CLI bootstrap for the first generation of .g.cs from .sharq files.
/// Solves the chicken-and-egg problem: AssetPostprocessor does not run
/// until the project compiles, and the project does not compile without generated *Content classes.
///
/// Usage:
///   dotnet run --project sus-core/Tools~/SharqBootstrap -- [project-root]
///
/// The generator is pure C# (string → string), with no Unity dependencies.
/// Scans {project-root}/Assets/**/*.sharq, writes .g.cs into SusConfig.GeneratedDirectory.
/// USS (.g.uss, _scoped, _static) is generated by the ASSETPOSTPROCESSOR on the next Unity open.
/// </summary>
class Program
{
    static int Main(string[] args)
    {
        var projectRoot = args.Length > 0
            ? Path.GetFullPath(args[0])
            : Directory.GetCurrentDirectory();

        if (!Directory.Exists(projectRoot))
        {
            Console.Error.WriteLine($"[SharqBootstrap] ERROR: project root not found: {projectRoot}");
            return 1;
        }

        Directory.SetCurrentDirectory(projectRoot);
        Console.WriteLine($"[SharqBootstrap] Project root: {projectRoot}");

        // SusConfig loads from Assets/sus.config.json (relative to CWD)
        var config = Sharq.Core.Editor.SusConfig.Instance;
        Console.WriteLine($"[SharqBootstrap] SharqDirectory   = {config.SharqDirectory}");
        Console.WriteLine($"[SharqBootstrap] GeneratedDirectory = {config.GeneratedDirectory}");

        var absSharqDir = Path.GetFullPath(config.SharqDirectory);
        if (!Directory.Exists(absSharqDir))
        {
            Console.Error.WriteLine($"[SharqBootstrap] ERROR: SharqDirectory not found: {absSharqDir}");
            return 1;
        }

        var sharqFiles = Directory.GetFiles(absSharqDir, "*.sharq", SearchOption.AllDirectories);
        Console.WriteLine($"[SharqBootstrap] Found {sharqFiles.Length} .sharq file(s)");

        var generatedDir = Path.GetFullPath(config.GeneratedDirectory);
        Directory.CreateDirectory(generatedDir);

        var generatedCount = 0;
        var skippedCount = 0;
        var failedCount = 0;

        foreach (var sharqPath in sharqFiles)
        {
            try
            {
                var content = File.ReadAllText(sharqPath);
                var model = Sharq.Core.Editor.SharqFileParser.Parse(content, sharqPath);

                if (string.IsNullOrEmpty(model.TemplateXml))
                {
                    Console.WriteLine($"  SKIP  {Path.GetFileName(sharqPath)}  (no &lt;template&gt;)");
                    skippedCount++;
                    continue;
                }

                var generatedCSharp = Sharq.Core.Editor.BuildMethodGenerator.Generate(model);
                var gcsPath = Path.Combine(generatedDir, $"{model.ClassName}.g.cs");
                File.WriteAllText(gcsPath, generatedCSharp, Encoding.UTF8);

                Console.WriteLine($"  OK    {model.ClassName}.g.cs  ({Path.GetFileName(sharqPath)})");
                generatedCount++;
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"  FAIL  {Path.GetFileName(sharqPath)}  — {ex.Message}");
                failedCount++;
            }
        }

        var summary = $"[SharqBootstrap] Done. {generatedCount} generated";
        if (skippedCount > 0) summary += $", {skippedCount} skipped";
        if (failedCount > 0) summary += $", {failedCount} FAILED";
        Console.WriteLine(summary);

        return failedCount > 0 ? 1 : 0;
    }
}
