using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace Sharq.Core.Editor
{
    /// <summary>
    /// Generates the Build() method body from a parsed template tree.
    /// Phase 3: v-if, v-show, v-for, :text, :class, @event, slot/v-slot.
    ///
    /// P2.8: generation state (var/style counters + collected inline styles) lives on
    /// the INSTANCE, not in static fields, so a parallel batch (one generator per file)
    /// is thread-safe. Use <see cref="Generate(SharqFileModel)"/> for the code-only
    /// convenience, or new an instance to read <see cref="GeneratedStyles"/> from the
    /// same run (see <c>SharqCompilePipeline</c>).
    /// </summary>
    internal sealed class BuildMethodGenerator
    {
        private int _varCounter;
        private readonly StaticStyleRegistry _styles = new();

        /// <summary>
        /// Maps raw inline style strings to generated USS class names, populated by the
        /// most recent <see cref="GenerateCode"/> call on THIS instance.
        /// Key: "font-size: 24px; color: white;", Value: "sharq-ComponentName-s0".
        /// Deduplicates — two elements with identical styles share one class.
        /// </summary>
        internal IReadOnlyDictionary<string, string> GeneratedStyles => _styles.Styles;

        /// <summary>
        /// Code-only convenience entry point (tests / CLI). Creates a throwaway instance;
        /// callers that also need <see cref="GeneratedStyles"/> should new an instance and
        /// call <see cref="GenerateCode"/> so code and styles come from the same run.
        /// </summary>
        public static string Generate(SharqFileModel model)
            => new BuildMethodGenerator().GenerateCode(model);

        /// <summary>
        /// Source path for the generated file's header, relative to the project folder.
        /// An absolute path would bake the machine that ran the generator into a file teams
        /// commit, so every teammate's regeneration shows a diff that is only their own path.
        /// </summary>
        private static string SourceLabel(SharqFileModel model)
        {
            var path = model.SourcePath;
            if (string.IsNullOrEmpty(path))
                return model.ClassName + ".sharq";

            path = path.Replace('\\', '/');
            var projectRoot = UnityEngine.Application.dataPath;              // <project>/Assets
            projectRoot = projectRoot.Substring(0, projectRoot.LastIndexOf('/') + 1);
            return path.StartsWith(projectRoot, StringComparison.OrdinalIgnoreCase)
                ? path.Substring(projectRoot.Length)
                : System.IO.Path.GetFileName(path);
        }

        public string GenerateCode(SharqFileModel model)
        {
            if (model?.TemplateXml == null)
                return GenerateEmpty(model?.ClassName ?? "Unknown", model?.BaseClass, model?.Namespace);

            var root = TemplateParser.Parse(model.TemplateXml, model.ClassName);
            var sb = new StringBuilder();
            _varCounter = 0;
            _styles.Clear();

            ScriptBodyTransformer.ApplyDirectives(model);

            // ─── Class header ────────────────────────────────────────
            var hasCreateProp = ScriptBodyTransformer.HasCreateProperty(model.ScriptBody);
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using UnityEngine.UIElements;");
            sb.AppendLine("using Sharq.Core;");
            if (hasCreateProp)
                sb.AppendLine("using Unity.Properties;");
            foreach (var useNs in model.Usings)
            {
                if (useNs != "UnityEngine" && useNs != "Sharq.Core"
                    && useNs != "System" && useNs != "System.Collections.Generic"
                    && useNs != "Unity.Properties" && useNs != "UnityEngine.UIElements")
                    sb.AppendLine($"using {useNs};");
            }
            if (model.Usings.Contains("UnityEngine"))
                sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine($"// Auto-generated by SharqSourceGenerator from {SourceLabel(model)}");
            // Generated code has no nullable annotations (fields are assigned in Build(),
            // not the ctor) — disable nullable analysis to avoid CS8618/CS86xx noise.
            sb.AppendLine("#nullable disable");
            var classNs = model.Namespace?.Trim();
            var hasNs = !string.IsNullOrEmpty(classNs);
            if (hasNs)
            {
                sb.AppendLine($"namespace {classNs}");
                sb.AppendLine("{");
            }
            // Base class: $extends directive, default SusComponent. The base MUST derive
            // from SusComponent so the whole hierarchy stays uniform (C2 two-tier model).
            var baseClass = string.IsNullOrEmpty(model.BaseClass) ? "SusComponent" : model.BaseClass;
            var indent = hasNs ? "    " : "";
            sb.AppendLine($"{indent}[UxmlElement]");
            sb.AppendLine($"{indent}public partial class {model.ClassName} : {baseClass}");
            sb.AppendLine($"{indent}{{");

            // ─── Script body (injected via ScriptBodyTransformer) ────
            var memberIndent = indent + "    ";
            ScriptBodyTransformer.EmitMembers(sb, model.ScriptBody, memberIndent);

            // ─── Build() ─────────────────────────────────────────────
            var bodyIndent = memberIndent + "    ";
            sb.AppendLine($"{memberIndent}protected override void Build()");
            sb.AppendLine($"{memberIndent}{{");
            sb.AppendLine($"{bodyIndent}LoadCompanionStyleSheets();");
            sb.AppendLine();
            // Apply scoped CSS
            if (model.IsStyleScoped)
            {
                var hash = GenerateScopedHash(model.ClassName);
                sb.AppendLine($"{bodyIndent}ApplyScopedAttribute(\"{hash}\");");
            }

            // Root class / style (bare AddToClassList for class; this. for style — preserve emit shape)
            if (root.Attributes.TryGetValue("class", out var rootClass))
                EmitClassListAdds(sb, bodyIndent, receiver: null, rootClass);

            // Root :class binding (same logic as GenerateCommonAttributes)
            foreach (var attr in root.Attributes)
            {
                if (attr.Key == ":class")
                {
                    var val = attr.Value.Trim();
                    if (val.StartsWith("{") && val.EndsWith("}"))
                    {
                        var pairs = ParseClassObjectSyntax(val);
                        foreach (var (cls, cond) in pairs)
                        {
                            sb.AppendLine($"{bodyIndent}BindClass(this, \"{cls}\", () => {TranslateExpr(cond)});");
                        }
                    }
                }
            }

            if (root.Attributes.TryGetValue("style", out var rootStyle))
                EmitRegisteredStyle(sb, bodyIndent, "this", model.ClassName, rootStyle);

            // Generate children (handles v-if/v-else-if/v-else chains)
            if (root.Children.Count > 0)
            {
                GenerateChildren(sb, root.Children, bodyIndent, "this", model);
            }

            sb.AppendLine($"{memberIndent}}}");
            sb.AppendLine();

            // ─── Close class (+ optional namespace) ───────────────────
            sb.AppendLine($"{indent}}}");
            if (hasNs)
                sb.AppendLine("}");

            return sb.ToString();
        }

        private static string GenerateEmpty(string className, string baseClass = null, string classNamespace = null)
        {
            var b = string.IsNullOrEmpty(baseClass) ? "SusComponent" : baseClass;
            var ns = classNamespace?.Trim();
            if (string.IsNullOrEmpty(ns))
            {
                return $@"[UxmlElement]
public partial class {className} : {b}
{{
    protected override void Build()
    {{
        LoadCompanionStyleSheets();
        // Empty component (no template)
    }}
}}";
            }

            return $@"namespace {ns}
{{
    [UxmlElement]
    public partial class {className} : {b}
    {{
        protected override void Build()
        {{
            LoadCompanionStyleSheets();
            // Empty component (no template)
        }}
    }}
}}";
        }

        /// <summary>
        /// Iterates children, detecting and grouping v-if/v-else-if/v-else chains.
        /// v-else-if / v-else without a preceding v-if are emitted as warnings.
        /// </summary>
        private void GenerateChildren(StringBuilder sb, List<TemplateNode> children,
            string indent, string parentVar, SharqFileModel model)
        {
            for (int i = 0; i < children.Count; i++)
            {
                var child = children[i];

                // v-else-if / v-else without preceding v-if — skip with comment
                if (child.Attributes.ContainsKey(Constants.VElseIf) ||
                    child.Attributes.ContainsKey(Constants.VElse))
                {
                    sb.AppendLine($"{indent}// WARNING: {child.TagName} has v-else-if/v-else without preceding v-if");
                    continue;
                }

                // v-if found? Check for following v-else-if/v-else chain
                if (child.Attributes.ContainsKey(Constants.VIf))
                {
                    var chain = new List<TemplateNode> { child };
                    int j = i + 1;
                    while (j < children.Count)
                    {
                        var next = children[j];
                        if (next.Attributes.ContainsKey(Constants.VElseIf) ||
                            next.Attributes.ContainsKey(Constants.VElse))
                        {
                            chain.Add(next);
                            j++;
                        }
                        else
                        {
                            break;
                        }
                    }
                    if (chain.Count > 1)
                    {
                        GenerateConditionalChain(sb, chain, indent, parentVar, model);
                        i = j - 1; // skip consumed siblings
                        continue;
                    }
                }

                GenerateElement(sb, child, indent, parentVar, model);
            }
        }

        /// <summary>
        /// Generates if / else-if / else chain from v-if/v-else-if/v-else siblings.
        /// All elements share the same parentVar.
        /// </summary>
        private void GenerateConditionalChain(StringBuilder sb, List<TemplateNode> chain,
            string indent, string parentVar, SharqFileModel model)
        {
            for (int k = 0; k < chain.Count; k++)
            {
                var node = chain[k];
                string condition = null;

                if (node.Attributes.TryGetValue(Constants.VIf, out var vIfCond))
                {
                    condition = vIfCond;
                }
                else if (node.Attributes.TryGetValue(Constants.VElseIf, out var vElseIfCond))
                {
                    condition = vElseIfCond;
                }

                sb.AppendLine();
                sb.Append(k == 0
                    ? $"{indent}if ({condition})"
                    : condition != null
                        ? $"{indent}else if ({condition})"
                        : $"{indent}else");
                sb.AppendLine($"{indent}{{");

                // Clean v-if/v-else-if/v-else from attributes so they don't interfere
                node.Attributes.Remove(Constants.VIf);
                node.Attributes.Remove(Constants.VElseIf);
                node.Attributes.Remove(Constants.VElse);

                // Create the element and add to parent (no BindVisibility wrapping)
                var varName = $"__el_{_varCounter++}";
                var typeName = ResolveTypeName(node.TagName);
                sb.AppendLine($"{indent}    var {varName} = new {typeName}();");
                GenerateCommonAttributes(sb, node, indent + "    ", varName, typeName, model);

                // v-show
                if (node.Attributes.TryGetValue(Constants.VShow, out var showCond))
                {
                    sb.AppendLine($"{indent}    BindShow({varName}, () => {TranslateExpr(showCond)});");
                }

                // v-slot
                var slotAttr = FindSlotAttr(node);
                if (slotAttr != null)
                {
                    var slotName = string.IsNullOrEmpty(slotAttr.Value.Value) ? "default" : slotAttr.Value.Value;
                    sb.AppendLine($"{indent}    RegisterSlotContent(\"{slotName}\", {varName}, null);");
                }

                // Nested children
                if (node.Children.Count > 0)
                {
                    GenerateChildren(sb, node.Children, indent + "    ", varName, model);
                }

                sb.AppendLine($"{indent}    {parentVar}.Add({varName});");
                sb.AppendLine($"{indent}}}");
            }
        }

        // Expression helpers live in ExpressionTranslator (R-B3 / T-1108).
        // Thin wrappers keep existing call sites and golden-test access stable.
        private static string ResolvePropExpr(string expr, SharqFileModel model)
            => ExpressionTranslator.ResolvePropExpr(expr, model);

        private static string ResolveCollectionExpr(string expr, SharqFileModel model)
            => ExpressionTranslator.ResolveCollectionExpr(expr, model);

        internal static string TranslateExpr(string expr)
            => ExpressionTranslator.TranslateExpr(expr);

        internal static string TranslateBindingExpr(string expr)
            => ExpressionTranslator.TranslateBindingExpr(expr);

        private void GenerateElement(StringBuilder sb, TemplateNode node, string indent, string parentVar, SharqFileModel model)
        {
            if (node == null) return;

            var typeName = ResolveTypeName(node.TagName);

            // ─── v-for ───────────────────────────────────────────
            if (node.Attributes.TryGetValue(Constants.VFor, out var vForExpr) && node.Children.Count > 0)
            {
                GenerateForElement(sb, node, indent, parentVar, vForExpr, model);
                return;
            }

            // ─── <slot> tag ───────────────────────────────────────
            if (node.TagName == "slot")
            {
                GenerateSlot(sb, node, indent, parentVar, model);
                return;
            }

            var varName = $"__el_{_varCounter++}";

            // Create element first; BindVisibility runs AFTER parent.Add (see below).
            sb.AppendLine($"{indent}var {varName} = new {typeName}();");

            // v-if condition captured; bind after Add so first hide can RemoveFromHierarchy
            var hasIf = node.Attributes.TryGetValue(Constants.VIf, out var ifCondition);
            string transitionName = null;
            if (hasIf)
            {
                sb.AppendLine($"{indent}// v-if=\"{ifCondition}\"");
                node.Attributes.TryGetValue(Constants.Transition, out transitionName);
            }

            // v-show
            var hasShow = node.Attributes.TryGetValue(Constants.VShow, out var showCondition);

            // ─── Common: class, style, bindings, events ──────────
            GenerateCommonAttributes(sb, node, indent, varName, typeName, model);

            // v-show after children
            if (hasShow)
            {
                sb.AppendLine($"{indent}// v-show=\"{showCondition}\"");
                sb.AppendLine($"{indent}BindShow({varName}, () => {TranslateExpr(showCondition)});");
            }

            // v-slot: register as slot content
            var slotAttr = FindSlotAttr(node);
            if (slotAttr != null)
            {
                var slotName = string.IsNullOrEmpty(slotAttr.Value.Value) ? "default" : slotAttr.Value.Value;
                sb.AppendLine($"{indent}// v-slot:{slotName}");
                sb.AppendLine($"{indent}RegisterSlotContent(\"{slotName}\", {varName}, null);");
            }

            // Recursively generate children (handles v-if/v-else-if/v-else chains)
            if (node.Children.Count > 0)
            {
                GenerateChildren(sb, node.Children, indent, varName, model);
            }

            // Add to parent, THEN BindVisibility (so false condition removes from tree)
            sb.AppendLine($"{indent}{parentVar}.Add({varName});");
            if (hasIf)
            {
                if (!string.IsNullOrEmpty(transitionName) && transitionName != "none")
                {
                    sb.AppendLine($"{indent}BindTransitionVisibility({varName}, () => {TranslateExpr(ifCondition)}, \"{EscapeCSharpString(transitionName)}\");");
                }
                else
                {
                    sb.AppendLine($"{indent}BindVisibility({varName}, () => {TranslateExpr(ifCondition)});");
                }
            }
        }

        /// <summary>
        /// Generates a reactive BindList call for the v-for directive.
        /// Parses "itemVar in collectionExpr" and generates a lambda
        /// that creates child elements for each item.
        /// When item type can be inferred, uses typed BindList&lt;T&gt; for property access.
        /// </summary>
        private void GenerateForElement(StringBuilder sb, TemplateNode node, string indent, string parentVar, string vForExpr, SharqFileModel model)
        {
            // Parse: "item in Items" or "item, index in Items"
            var match = Regex.Match(vForExpr, @"^\s*(\w+)(?:\s*,\s*(\w+))?\s+in\s+(.+)$");
            if (!match.Success)
            {
                sb.AppendLine($"{indent}// v-for parse error: \"{vForExpr}\"");
                return;
            }

            var itemVar = match.Groups[1].Value;
            var indexVar = match.Groups[2].Value; // optional
            var collectionExpr = match.Groups[3].Value.Trim();

            // Infer item type from script fields
            var itemType = InferItemType(model, collectionExpr);
            var isTyped = itemType != null;

            var keyExpr = "";
            node.Attributes.TryGetValue(Constants.KeyBind, out keyExpr);

            var varName = $"__el_{_varCounter++}";
            var subIndent = indent + "    ";

            // Container
            sb.AppendLine($"{indent}// v-for=\"{vForExpr}\"{(isTyped ? $" (typed: {itemType})" : "")}");
            sb.AppendLine($"{indent}var {varName} = new VisualElement();");

            // class / style on container
            if (node.Attributes.TryGetValue("class", out var className))
                EmitClassListAdds(sb, indent, varName, className);
            if (node.Attributes.TryGetValue("style", out var styleStr))
                EmitRegisteredStyle(sb, indent, varName, model.ClassName, styleStr);

            // Reactive v-for: BindList wraps the collection in a Func<> so the
            // ReactiveEffect re-renders when the underlying Prop/collection changes.
            // (BindListFor was a one-shot render — non-reactive, kept for legacy.)
            var reactiveSource = ResolveCollectionExpr(collectionExpr, model);
            if (isTyped)
                sb.AppendLine($"{indent}BindList<{itemType}>(");
            else
                sb.AppendLine($"{indent}BindList(");
            sb.AppendLine($"{indent}    {varName},");
            sb.AppendLine($"{indent}    () => {reactiveSource},");
            sb.AppendLine($"{indent}    ({itemVar}, __i) => {{");

            // Generate template children with typed/untyped info
            // ALWAYS create __wrap so nested children can reference it
            sb.AppendLine($"{subIndent}var __wrap = new VisualElement();");
            if (node.Children.Count == 1)
            {
                GenerateForTemplate(sb, node.Children[0], subIndent, itemVar, isTyped, model.ClassName);
            }
            else if (node.Children.Count > 1)
            {
                foreach (var child in node.Children)
                {
                    GenerateForTemplate(sb, child, subIndent, itemVar, isTyped, model.ClassName);
                }
            }
            sb.AppendLine($"{subIndent}return __wrap;");

            sb.Append($"{indent}    }}");
            if (!string.IsNullOrEmpty(keyExpr))
            {
                // Key selector: Func<T, object> (typed) / Func<object, object> (untyped).
                // Untyped must NOT use ((dynamic)item).X — System.Dynamic fails under IL2CPP/AOT.
                // Emit GetItemMember reflection helper instead (cached accessors on SusComponent).
                string keyLambda;
                if (keyExpr == itemVar)
                    keyLambda = $"{itemVar} => {itemVar}";
                else if (keyExpr.StartsWith(itemVar + "."))
                {
                    if (isTyped)
                        keyLambda = $"{itemVar} => {keyExpr}";
                    else
                    {
                        var memberPath = keyExpr.Substring(itemVar.Length + 1);
                        keyLambda = $"{itemVar} => GetItemMember({itemVar}, \"{EscapeCSharpString(memberPath)}\")";
                    }
                }
                else
                    keyLambda = $"{itemVar} => {keyExpr}";
                sb.AppendLine();
                sb.AppendLine($"{indent}    , {keyLambda}");
            }
            sb.AppendLine();
            sb.AppendLine($"{indent});");

            // Add container to parent
            sb.AppendLine($"{indent}{parentVar}.Add({varName});");
        }

        /// <summary>
        /// Generates a single template element inside a v-for lambda.
        /// When isTyped: item.Prop is accessed directly (IL2CPP-safe).
        /// When !isTyped: falls back to item?.ToString().
        /// </summary>
        private void GenerateForTemplate(StringBuilder sb, TemplateNode child, string indent, string itemVar, bool isTyped, string className)
        {
            var varName = $"__el_{_varCounter++}";
            var typeName = ResolveTypeName(child.TagName);

            sb.AppendLine($"{indent}var {varName} = new {typeName}();");

            if (child.Attributes.TryGetValue("class", out var clsVal))
                EmitClassListAdds(sb, indent, varName, clsVal);
            if (child.Attributes.TryGetValue("style", out var stVal))
                EmitRegisteredStyle(sb, indent, varName, className, stVal);

            // :text → typed or untyped
            if (typeName == "Label" && TryGetBindAttr(child.Attributes, "text", out var textExpr))
            {
                if (isTyped)
                {
                    // Typed: item.Name?.ToString() ?? "" — expr already IL2CPP-safe as written
                    sb.AppendLine($"{indent}BindText({varName}, () => {TranslateBindingExpr(textExpr)}?.ToString() ?? \"\");");
                }
                else
                {
                    // Untyped: item?.ToString() ?? ""
                    var resolved = ResolveItemRef(textExpr, itemVar);
                    sb.AppendLine($"{indent}BindText({varName}, () => {TranslateBindingExpr(resolved)}?.ToString() ?? \"\");");
                }
            }

            // @events — with modifiers support
            foreach (var attr in child.Attributes)
            {
                if (attr.Key.StartsWith(Constants.EventPrefix))
                {
                    GenerateEventCallback(sb, indent, varName, attr.Key, attr.Value, typeName);
                }
            }

            // Recursive children
            if (child.Children.Count > 0)
            {
                foreach (var sub in child.Children)
                {
                    GenerateForTemplate(sb, sub, indent, itemVar, isTyped, className);
                }
            }

            sb.AppendLine($"{indent}__wrap.Add({varName});");
        }

        /// <summary>
        /// Infers the element type of a collection field from &lt;script&gt;.
        /// E.g. "List&lt;UnitData&gt; Items" → "UnitData"
        /// Returns null if inference fails.
        /// </summary>
        private static string InferItemType(SharqFileModel model, string collectionExpr)
        {
            if (string.IsNullOrEmpty(model.ScriptBody)) return null;

            // Strip "this." prefix
            var collectionVar = collectionExpr.StartsWith("this.")
                ? collectionExpr.Substring(5)
                : collectionExpr;

            // Match: List<T> varName  /  IList<T> varName  /  IEnumerable<T> varName
            var pattern = $@"(?:List|IList|IEnumerable|ObservableList)<([^>]+)>\s+{Regex.Escape(collectionVar)}\b";
            var m = Regex.Match(model.ScriptBody, pattern);
            if (m.Success) return m.Groups[1].Value.Trim();

            // Match: Prop<List<T>> varName  /  Prop<IList<T>> varName  (reactive wrapper)
            pattern = $@"Prop<(?:List|IList|IEnumerable|ObservableList)<([^>]+)>>\s+{Regex.Escape(collectionVar)}\b";
            m = Regex.Match(model.ScriptBody, pattern);
            if (m.Success) return m.Groups[1].Value.Trim();

            // Array: T[] varName
            pattern = $@"([\w.]+)\[\]\s+{Regex.Escape(collectionVar)}\b";
            m = Regex.Match(model.ScriptBody, pattern);
            if (m.Success) return m.Groups[1].Value.Trim();

            return null;
        }

        /// <summary>
        /// Resolves item references in bind expressions (untyped fallback).
        /// "Greeting" → unchanged (component field)
        /// "item.Name" → "item" (nested props via ToString fallback)
        /// "item" → "item" (reference to lambda param, .ToString() appended by caller)
        /// </summary>
        private static string ResolveItemRef(string expr, string itemVar)
        {
            if (expr == itemVar)
                return itemVar;
            if (expr.StartsWith(itemVar + "."))
                return itemVar;
            return expr;
        }

        /// <summary>
        /// Generates slot projection: GetSlotContainer + scoped props (F3) + BuildSlot.
        /// Scoped props come from bind attributes on &lt;slot&gt;: <c>&lt;slot :item="Row"&gt;</c>.
        /// </summary>
        private void GenerateSlot(StringBuilder sb, TemplateNode node, string indent, string parentVar, SharqFileModel model)
        {
            var slotName = "default";
            if (node.Attributes.TryGetValue("name", out var name))
                slotName = name;

            sb.AppendLine($"{indent}// <slot name=\"{slotName}\">");
            sb.AppendLine($"{indent}var __slot_{slotName} = GetSlotContainer(\"{slotName}\");");
            sb.AppendLine($"{indent}{parentVar}.Add(__slot_{slotName});");

            // F3: scoped slot props from :prop="expr" on <slot>
            foreach (var attr in node.Attributes)
            {
                if (!attr.Key.StartsWith(Constants.BindPrefix)) continue;
                var propName = attr.Key.Substring(1);
                if (propName == "name" || propName == "class" || propName == "key") continue;
                sb.AppendLine($"{indent}ProvideSlotProp(\"{slotName}\", \"{propName}\", {TranslateExpr(attr.Value)});");
            }

            // Fallback content: children of <slot> rendered into the slot container
            if (node.Children.Count > 0)
            {
                GenerateChildren(sb, node.Children, indent, $"__slot_{slotName}", model);
            }
            sb.AppendLine($"{indent}BuildSlot(\"{slotName}\", null, __slot_{slotName});");
        }

        /// <summary>
        /// Finds v-slot or v-slot:name attribute on a node.
        /// </summary>
        private static KeyValuePair<string, string>? FindSlotAttr(TemplateNode node)
        {
            foreach (var attr in node.Attributes)
            {
                if (attr.Key == "v-slot")
                    return new KeyValuePair<string, string>("v-slot", attr.Value);
                if (attr.Key.StartsWith("v-slot:"))
                    return new KeyValuePair<string, string>("v-slot", attr.Key.Substring("v-slot:".Length));
            }
            return null;
        }

        // ─── Common attribute generation (shared between regular + v-for) ────

        private void GenerateCommonAttributes(StringBuilder sb, TemplateNode node, string indent, string varName, string typeName, SharqFileModel model)
        {
            if (node.Attributes.TryGetValue("class", out var clsName))
                EmitClassListAdds(sb, indent, varName, clsName);

            // name — emit for ALL elements (built-in UITK + custom components)
            if (node.Attributes.TryGetValue("name", out var nameVal))
            {
                sb.AppendLine($"{indent}{varName}.name = \"{EscapeCSharpString(nameVal)}\";");
            }

            if (node.Attributes.TryGetValue("style", out var styleStr))
                EmitRegisteredStyle(sb, indent, varName, model?.ClassName ?? "", styleStr);

            // :text binding on Label (supports pipe converters: | format | upper | round)
            if (typeName == "Label" && TryGetBindAttr(node.Attributes, "text", out var textExpr))
            {
                sb.AppendLine($"{indent}BindText({varName}, () => {TranslateBindingExpr(textExpr)});");
            }

            // text="literal" on built-in Label / Button (non-bound text attribute)
            // Custom components (e.g. SusButton) get text as a prop via the block below.
            if (!IsCustomComponent(typeName) && node.Attributes.TryGetValue("text", out var literalText))
            {
                if (!literalText.StartsWith(":") && !literalText.StartsWith("@"))
                {
                    sb.AppendLine($"{indent}{varName}.text = \"{EscapeCSharpString(literalText)}\";");
                }
            }

            // text="literal" on custom components → SetChildProp
            if (IsCustomComponent(typeName) && node.Attributes.TryGetValue("text", out var customText))
            {
                if (!customText.StartsWith(":") && !customText.StartsWith("@"))
                {
                    sb.AppendLine($"{indent}SusComponent.SetChildProp({varName}, \"text\", \"{EscapeCSharpString(customText)}\");");
                }
            }

            // :class binding — object syntax: { class1: cond1, class2: cond2 }
            foreach (var attr in node.Attributes)
            {
                if (attr.Key.StartsWith(Constants.BindPrefix) && attr.Key != ":text")
                {
                    var bindKey = attr.Key.Substring(1);
                    if (bindKey == "class")
                    {
                        var val = attr.Value.Trim();
                        if (val.StartsWith("{") && val.EndsWith("}"))
                        {
                            // Parse { active: isActive, disabled: isDisabled }
                            var pairs = ParseClassObjectSyntax(val);
                            foreach (var (cls, cond) in pairs)
                            {
                                sb.AppendLine($"{indent}BindClass({varName}, \"{cls}\", () => {TranslateExpr(cond)});");
                            }
                        }
                        else
                        {
                            sb.AppendLine($"{indent}// :class=\"{attr.Value}\"");
                        }
                    }
                }
            }

            // @event handlers (with optional .stop / .once modifiers)
            foreach (var attr in node.Attributes)
            {
                if (attr.Key.StartsWith(Constants.EventPrefix))
                {
                    GenerateEventCallback(sb, indent, varName, attr.Key, attr.Value, typeName);
                }
            }

            // ─── Custom component prop passing ─────────────────────────
            if (IsCustomComponent(typeName))
            {
                // Known attributes to skip (already handled above):
                // class, style, text, $MainElement, v-if, v-else-if, v-else,
                // v-show, v-for, v-slot, :class, :text, @*, key
                var skipAttrs = new HashSet<string>
                {
                    "class", "style", "text", "name", Constants.MainElement,
                    Constants.VIf, Constants.VElseIf, Constants.VElse,
                    Constants.VShow, Constants.VFor, "v-slot", "key", Constants.Transition
                };

                foreach (var attr in node.Attributes)
                {
                    var key = attr.Key;

                    // Skip already-handled and structural attributes
                    if (skipAttrs.Contains(key)) continue;
                    if (key.StartsWith(Constants.EventPrefix)) continue;
                    if (key.StartsWith(Constants.BindPrefix) && key != ":text" && key != ":class")
                    {
                        // Reactive prop binding (case-insensitive): :propName="expr"
                        var propName = key.Substring(1); // remove ':'
                        sb.AppendLine($"{indent}// :{propName}=\"{attr.Value}\" → reactive prop bind");
                        var expr = attr.Value.Replace("'", "\"");
                        expr = ResolvePropExpr(expr, model);
                        sb.AppendLine($"{indent}BindChildProp({varName}, \"{propName}\", () => {expr});");
                        continue;
                    }
                    if (key.StartsWith(Constants.BindPrefix))
                        continue; // already handled: :text, :class

                    // Literal prop: propName="value" — try typed assignment first
                    if (key.StartsWith("$") || key.StartsWith("v-"))
                        continue;

                    var value = attr.Value;
                    if (string.IsNullOrEmpty(value))
                    {
                        // Boolean attribute (e.g., <sus:SusButton disabled>)
                        sb.AppendLine($"{indent}SusComponent.SetChildProp({varName}, \"{key}\", true);");
                    }
                    else
                    {
                        sb.AppendLine($"{indent}SusComponent.SetChildProp({varName}, \"{key}\", \"{EscapeCSharpString(value)}\");");
                    }
                }
            }
        }

        /// <summary>
        /// Emit <c>AddToClassList</c> for each token in a space-separated class attribute.
        /// <paramref name="receiver"/> null → bare <c>AddToClassList</c> (root); else <c>{receiver}.AddToClassList</c>.
        /// </summary>
        private static void EmitClassListAdds(StringBuilder sb, string indent, string receiver, string classAttr)
        {
            if (string.IsNullOrEmpty(classAttr)) return;
            var classes = classAttr.Split(' ').Where(c => !string.IsNullOrEmpty(c));
            foreach (var cls in classes)
            {
                if (string.IsNullOrEmpty(receiver))
                    sb.AppendLine($"{indent}AddToClassList(\"{cls}\");");
                else
                    sb.AppendLine($"{indent}{receiver}.AddToClassList(\"{cls}\");");
            }
        }

        /// <summary>
        /// Register inline style → USS class and emit AddToClassList for that class.
        /// </summary>
        private void EmitRegisteredStyle(StringBuilder sb, string indent, string receiver, string componentName, string styleStr)
        {
            var styleClass = _styles.Register(componentName, styleStr);
            if (styleClass == null) return;
            if (string.IsNullOrEmpty(receiver))
                sb.AppendLine($"{indent}AddToClassList(\"{styleClass}\");");
            else
                sb.AppendLine($"{indent}{receiver}.AddToClassList(\"{styleClass}\");");
        }

        /// <summary>
        /// Maps a template <c>@event</c> name to a UITK event type.
        /// Unknown names must NOT silently fall back to <c>EventBase&lt;EventBase&gt;</c>
        /// (that type is invalid and produces opaque compile failures).
        /// </summary>
        private static bool TryMapEventType(string eventName, out string eventType)
        {
            eventType = eventName.ToLowerInvariant() switch
            {
                "click" => "UnityEngine.UIElements.ClickEvent",
                "mouseenter" => "UnityEngine.UIElements.MouseEnterEvent",
                "mouseleave" => "UnityEngine.UIElements.MouseLeaveEvent",
                "change" => "UnityEngine.UIElements.ChangeEvent<string>",
                _ => null
            };
            return eventType != null;
        }

        // ─── Event modifiers ─────────────────────────────────────────

        /// <summary>
        /// Parses "@click.stop" → ("click", stop: true, once: false).
        /// </summary>
        private static (string eventName, bool stop, bool once) ParseEventModifiers(string rawKey)
        {
            var name = rawKey.StartsWith(Constants.EventPrefix)
                ? rawKey.Substring(1)
                : rawKey;
            bool stop = name.Contains(".stop");
            bool once = name.Contains(".once");
            name = name.Replace(".stop", "").Replace(".once", "");
            return (name, stop, once);
        }

        /// <summary>
        /// Generates RegisterCallback line (UITK events) or On() wiring
        /// (custom component events). Supports .stop / .once modifiers.
        /// </summary>
        private void GenerateEventCallback(StringBuilder sb, string indent, string varName,
            string rawKey, string handler, string typeName)
        {
            var (eventName, stop, once) = ParseEventModifiers(rawKey);

            // Custom component events (e.g. @save on <sus:SusButton>)
            if (IsCustomComponent(typeName))
            {
                if (stop && once)
                {
                    // .stop.once: self-unregistering wrapper
                    var cbVar = $"__cb_{_varCounter++}";
                    sb.AppendLine($"{indent}System.Action {cbVar} = null;");
                    sb.AppendLine($"{indent}{cbVar} = () => {{");
                    sb.AppendLine($"{indent}    {varName}.Off(\"{eventName}\", {cbVar});");
                    sb.AppendLine($"{indent}    {handler}();");
                    sb.AppendLine($"{indent}}};");
                    sb.AppendLine($"{indent}{varName}.On(\"{eventName}\", {cbVar});");
                }
                else if (once)
                {
                    var cbVar = $"__cb_{_varCounter++}";
                    sb.AppendLine($"{indent}System.Action {cbVar} = null;");
                    sb.AppendLine($"{indent}{cbVar} = () => {{");
                    sb.AppendLine($"{indent}    {varName}.Off(\"{eventName}\", {cbVar});");
                    sb.AppendLine($"{indent}    {handler}();");
                    sb.AppendLine($"{indent}}};");
                    sb.AppendLine($"{indent}{varName}.On(\"{eventName}\", {cbVar});");
                }
                else
                {
                    sb.AppendLine($"{indent}{varName}.On(\"{eventName}\", () => {handler}());");
                }
                // .stop on component events — no equivalent (child controls emission)
                if (stop && !once)
                {
                    sb.AppendLine($"{indent}// NOTE: .stop has no effect on custom component events (child controls emission)");
                }
                return;
            }

            // UITK events — unknown @event → #error (compiler diagnostic), not a bogus type.
            if (!TryMapEventType(eventName, out var eventType))
            {
                sb.AppendLine(
                    $"{indent}#error Sharq: unknown @event '{EscapeCSharpString(eventName)}' on UITK element. " +
                    "Supported: click, mouseenter, mouseleave, change. " +
                    "For custom component events use On()/Off(), or extend the Sharq event map.");
                return;
            }

            if (!stop && !once)
            {
                sb.AppendLine($"{indent}{varName}.RegisterCallback<{eventType}>(_ => {handler}());");
                return;
            }

            var cbVarU = $"__cb_{_varCounter++}";
            sb.AppendLine($"{indent}EventCallback<{eventType}> {cbVarU} = null;");
            sb.AppendLine($"{indent}{cbVarU} = evt => {{");

            if (once)
                sb.AppendLine($"{indent}    {varName}.UnregisterCallback<{eventType}>({cbVarU});");
            if (stop)
                sb.AppendLine($"{indent}    evt.StopPropagation();");
            sb.AppendLine($"{indent}    {handler}();");
            sb.AppendLine($"{indent}}};");
            sb.AppendLine($"{indent}{varName}.RegisterCallback<{eventType}>({cbVarU});");
        }

        // ─── :class object syntax parser ──────────────────────────────

        /// <summary>
        /// Parses "{ active: isActive, disabled: isDisabled }" → [("active","isActive"), ("disabled","isDisabled")].
        /// Handles simple expressions; avoids splitting inside angle brackets for generics.
        /// </summary>
        private static List<(string className, string condition)> ParseClassObjectSyntax(string val)
        {
            var result = new List<(string, string)>();
            // Remove outer braces
            var inner = val.Substring(1, val.Length - 2).Trim();
            if (string.IsNullOrEmpty(inner)) return result;

            // Split by top-level commas (not inside angle brackets or parens)
            var segments = SplitTopLevel(inner, ',');
            foreach (var seg in segments)
            {
                var trimmed = seg.Trim();
                if (string.IsNullOrEmpty(trimmed)) continue;

                // Split by first colon
                var colonIdx = trimmed.IndexOf(':');
                if (colonIdx < 0) continue;
                var cls = trimmed.Substring(0, colonIdx).Trim().Trim('"', '\'');
                var cond = trimmed.Substring(colonIdx + 1).Trim();
                if (!string.IsNullOrEmpty(cls) && !string.IsNullOrEmpty(cond))
                    result.Add((cls, cond));
            }
            return result;
        }

        private static List<string> SplitTopLevel(string s, char delimiter)
        {
            var result = new List<string>();
            int depth = 0;
            int start = 0;
            for (int i = 0; i < s.Length; i++)
            {
                switch (s[i])
                {
                    case '<': case '(': case '{': depth++; break;
                    case '>': case ')': case '}': depth--; break;
                    default:
                        if (depth == 0 && s[i] == delimiter)
                        {
                            result.Add(s.Substring(start, i - start));
                            start = i + 1;
                        }
                        break;
                }
            }
            result.Add(s.Substring(start));
            return result;
        }

        private static string EscapeCSharpString(string s)
        {
            return s?.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static bool TryGetBindAttr(Dictionary<string, string> attrs, string bindKey, out string expr)
        {
            var key = $":{bindKey}";
            foreach (var kvp in attrs)
            {
                if (kvp.Key == key)
                {
                    expr = kvp.Value;
                    return true;
                }
            }
            expr = null;
            return false;
        }

        private static string ResolveTypeName(string tagName)
        {
            var name = tagName.Contains(":") ? tagName.Split(':')[1] : tagName;

            return name switch
            {
                "VisualElement" => "VisualElement",
                "Label" => "Label",
                "Button" => "Button",
                "TextField" => "TextField",
                "Toggle" => "Toggle",
                "Slider" => "Slider",
                "ScrollView" => "ScrollView",
                "Image" => "Image",
                "Box" => "Box",
                "GroupBox" => "GroupBox",
                "slot" => "VisualElement",
                "template" => "VisualElement",
                _ => name
            };
        }

        /// <summary>
        /// Returns true if the typeName is a custom component (not a UITK built-in element).
        /// Custom components receive prop assignments and component-level events.
        /// </summary>
        private static bool IsCustomComponent(string typeName)
        {
            return typeName switch
            {
                "VisualElement" => false,
                "Label" => false,
                "Button" => false,
                "TextField" => false,
                "Toggle" => false,
                "Slider" => false,
                "ScrollView" => false,
                "Image" => false,
                "Box" => false,
                "GroupBox" => false,
                _ => true
            };
        }

        private static string GenerateScopedHash(string className)
        {
            unchecked
            {
                int hash = 17;
                foreach (char c in className)
                    hash = hash * 31 + c;
                return $"s-{Math.Abs(hash):x6}";
            }
        }
    }
}
