// <auto-generated>
// GENERATED by the dimension-ladder emitter (`dim-scale --emit`) -- do not edit by hand.
// Projection of the dimension ladder: family -> rung -> (token name, value at the
// lg x default base step). A hand edit is reverted by the next emit and flagged by
// `dim-scale --check` (drift).
// </auto-generated>
using System;
using System.Collections.Generic;

namespace Sharq.Core.Editor
{
    /// <summary>
    /// The dimension ladder that <c>rung(&lt;family&gt;, &lt;rung&gt;)</c> resolves against. It ships
    /// inside the package, so a call resolves identically in every project that installs it.
    /// Values are the lg x default base step, in pixels.
    /// </summary>
    internal static class RungLadder
    {
        public const string SourceHash = "sha256:f5327d0d96123e2a0bdae3a7d90a9e22c45f5ee04d0ed2be02f3740c1fb0f1f2";
        public const int RungCount = 97;

        internal readonly struct Entry
        {
            public readonly string Rung;
            public readonly string Token;
            public readonly int Value;

            public Entry(string rung, string token, int value)
            {
                Rung = rung;
                Token = token;
                Value = value;
            }
        }

        /// <summary>Ladder families in source order (for the "available: ..." error text).</summary>
        public static readonly IReadOnlyList<string> Families = new[]
        {
            "space",
            "control-height",
            "font-size",
            "icon",
            "box",
            "control-box",
            "box-max",
            "panel",
            "wedge-h",
            "touch-min",
            "pill",
            "space-neg",
        };

        /// <summary>family -> rungs in ladder order.</summary>
        public static readonly IReadOnlyDictionary<string, Entry[]> Table =
            new Dictionary<string, Entry[]>(StringComparer.Ordinal)
            {
                ["space"] = new[]
                {
                    new Entry("2", "--sk-space-2", 2),
                    new Entry("4", "--sk-space-4", 4),
                    new Entry("6", "--sk-space-6", 6),
                    new Entry("8", "--sk-space-8", 8),
                    new Entry("10", "--sk-space-10", 10),
                    new Entry("12", "--sk-space-12", 12),
                    new Entry("16", "--sk-space-16", 16),
                    new Entry("20", "--sk-space-20", 20),
                    new Entry("24", "--sk-space-24", 24),
                    new Entry("28", "--sk-space-28", 28),
                    new Entry("32", "--sk-space-32", 32),
                    new Entry("40", "--sk-space-40", 40),
                    new Entry("48", "--sk-space-48", 48),
                },
                ["control-height"] = new[]
                {
                    new Entry("xs", "--sk-control-h-xs", 28),
                    new Entry("sm", "--sk-control-h-sm", 32),
                    new Entry("md", "--sk-control-h-md", 36),
                    new Entry("lg", "--sk-control-h-lg", 40),
                    new Entry("xl", "--sk-control-h-xl", 44),
                    new Entry("2xl", "--sk-control-h-2xl", 48),
                    new Entry("3xl", "--sk-control-h-3xl", 56),
                    new Entry("4xl", "--sk-control-h-4xl", 64),
                },
                ["font-size"] = new[]
                {
                    new Entry("caption", "--sk-font-caption", 10),
                    new Entry("xsmall", "--sk-font-xsmall", 10),
                    new Entry("small", "--sk-font-small", 12),
                    new Entry("body", "--sk-font-body", 14),
                    new Entry("subtitle", "--sk-font-subtitle", 16),
                    new Entry("large", "--sk-font-large", 16),
                    new Entry("heading", "--sk-font-heading", 20),
                },
                ["icon"] = new[]
                {
                    new Entry("xs", "--sk-icon-xs", 12),
                    new Entry("sm", "--sk-icon-sm", 16),
                    new Entry("md", "--sk-icon-md", 20),
                    new Entry("lg", "--sk-icon-lg", 24),
                    new Entry("xl", "--sk-icon-xl", 28),
                },
                ["box"] = new[]
                {
                    new Entry("xs", "--sk-box-xs", 48),
                    new Entry("sm", "--sk-box-sm", 56),
                    new Entry("md", "--sk-box-md", 64),
                    new Entry("lg", "--sk-box-lg", 72),
                    new Entry("xl", "--sk-box-xl", 88),
                    new Entry("2xl", "--sk-box-2xl", 96),
                    new Entry("3xl", "--sk-box-3xl", 104),
                },
                ["control-box"] = new[]
                {
                    new Entry("xs", "--sk-cbox-xs", 14),
                    new Entry("sm", "--sk-cbox-sm", 18),
                    new Entry("md", "--sk-cbox-md", 22),
                    new Entry("lg", "--sk-cbox-lg", 28),
                    new Entry("32", "--sk-cbox-32", 32),
                    new Entry("xl", "--sk-cbox-xl", 36),
                    new Entry("2xl", "--sk-cbox-2xl", 40),
                    new Entry("44", "--sk-cbox-44", 44),
                },
                ["box-max"] = new[]
                {
                    new Entry("tooltip", "--sk-tooltip-max-width", 320),
                    new Entry("menu-button", "--sk-menu-button-min-width", 240),
                    new Entry("nameplate-hp", "--sk-nameplate-hp-width", 80),
                    new Entry("nameplate-min", "--sk-nameplate-min-width", 120),
                },
                ["panel"] = new[]
                {
                    new Entry("140", "--sk-panel-140", 140),
                    new Entry("160", "--sk-panel-160", 160),
                    new Entry("180", "--sk-panel-180", 180),
                    new Entry("200", "--sk-panel-200", 200),
                    new Entry("220", "--sk-panel-220", 220),
                    new Entry("240", "--sk-panel-240", 240),
                    new Entry("280", "--sk-panel-280", 280),
                    new Entry("320", "--sk-panel-320", 320),
                    new Entry("360", "--sk-panel-360", 360),
                },
                ["wedge-h"] = new[]
                {
                    new Entry("1", "--sk-wedge-h-1", 10),
                    new Entry("2", "--sk-wedge-h-2", 12),
                    new Entry("3", "--sk-wedge-h-3", 14),
                    new Entry("4", "--sk-wedge-h-4", 16),
                    new Entry("5", "--sk-wedge-h-5", 18),
                    new Entry("6", "--sk-wedge-h-6", 20),
                    new Entry("7", "--sk-wedge-h-7", 22),
                    new Entry("8", "--sk-wedge-h-8", 24),
                    new Entry("9", "--sk-wedge-h-9", 26),
                    new Entry("10", "--sk-wedge-h-10", 28),
                    new Entry("11", "--sk-wedge-h-11", 30),
                    new Entry("12", "--sk-wedge-h-12", 32),
                    new Entry("13", "--sk-wedge-h-13", 34),
                    new Entry("14", "--sk-wedge-h-14", 36),
                    new Entry("15", "--sk-wedge-h-15", 38),
                    new Entry("16", "--sk-wedge-h-16", 40),
                },
                ["touch-min"] = new[]
                {
                    new Entry("min", "--sus-touch-min", 44),
                },
                ["pill"] = new[]
                {
                    new Entry("xs", "--sk-pill-xs", 14),
                    new Entry("sm", "--sk-pill-sm", 16),
                    new Entry("md", "--sk-pill-md", 18),
                    new Entry("lg", "--sk-pill-lg", 20),
                    new Entry("xl", "--sk-pill-xl", 22),
                    new Entry("2xl", "--sk-pill-2xl", 24),
                    new Entry("3xl", "--sk-pill-3xl", 28),
                },
                ["space-neg"] = new[]
                {
                    new Entry("2", "--sk-space-neg-2", -2),
                    new Entry("4", "--sk-space-neg-4", -4),
                    new Entry("6", "--sk-space-neg-6", -6),
                    new Entry("8", "--sk-space-neg-8", -8),
                    new Entry("10", "--sk-space-neg-10", -10),
                    new Entry("12", "--sk-space-neg-12", -12),
                    new Entry("16", "--sk-space-neg-16", -16),
                    new Entry("20", "--sk-space-neg-20", -20),
                    new Entry("24", "--sk-space-neg-24", -24),
                    new Entry("32", "--sk-space-neg-32", -32),
                    new Entry("40", "--sk-space-neg-40", -40),
                    new Entry("48", "--sk-space-neg-48", -48),
                },
            };

        public static bool TryGet(string family, string rung, out Entry entry)
        {
            entry = default;
            if (family == null || rung == null || !Table.TryGetValue(family, out var entries)) return false;
            foreach (var e in entries)
            {
                if (string.Equals(e.Rung, rung, StringComparison.Ordinal))
                {
                    entry = e;
                    return true;
                }
            }
            return false;
        }
    }
}
