using System;
using System.Collections.Generic;
using UnityEngine.UIElements;
using Sharq.Core;

// Auto-generated by SharqSourceGenerator from input.sharq
#nullable disable
[UxmlElement]
public partial class input : SusComponent
{
    // ─── From <script> ───
    public bool IsActive = false;

    protected override void Build()
    {
        LoadCompanionStyleSheets();

        BindClass(this, "active", () => IsActive);
    }

}
