using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Sharq.Core.Editor
{
    /// <summary>
    /// Locates and copies the pre-baked Setup starter from
    /// <c>Editor/Setup/Starter~</c> (committed in sus-core git with Generated/).
    /// </summary>
    internal static class SusStarterAssets
    {
        public const string StarterFolderName = "Starter~";

        /// <summary>Absolute path to <c>Editor/Setup/Starter~</c> inside the sus-core package.</summary>
        public static string GetStarterRoot()
        {
            // Fully qualify: UnityEditor.PackageInfo also exists (ambiguous with PackageManager).
            var info = UnityEditor.PackageManager.PackageInfo.FindForAssembly(
                typeof(SusStarterAssets).Assembly);
            if (info != null && !string.IsNullOrEmpty(info.resolvedPath))
            {
                var candidate = Path.Combine(info.resolvedPath, "Editor", "Setup", StarterFolderName);
                if (Directory.Exists(candidate))
                    return candidate;
            }

            // Fallback: walk up from this source file (file: / embedded package layouts).
            var guids = AssetDatabase.FindAssets("SusSetupWizard t:MonoScript");
            foreach (var guid in guids)
            {
                var scriptPath = AssetDatabase.GUIDToAssetPath(guid);
                if (string.IsNullOrEmpty(scriptPath) || !scriptPath.Contains("SusSetupWizard"))
                    continue;
                var setupDir = Path.GetDirectoryName(Path.GetFullPath(scriptPath));
                var candidate = Path.Combine(setupDir ?? "", StarterFolderName);
                if (Directory.Exists(candidate))
                    return candidate;
            }

            throw new DirectoryNotFoundException(
                "[SusSetup] Starter~ not found in sus-core package (Editor/Setup/Starter~).");
        }

        public static void CopyHomeScreen(string projectUiRootAbs)
        {
            var starter = GetStarterRoot();
            var sharqSrc = Path.Combine(starter, "HomeScreen.sharq");
            var gcsSrc = Path.Combine(starter, "Generated", "HomeScreen.g.cs");
            if (!File.Exists(sharqSrc) || !File.Exists(gcsSrc))
                throw new FileNotFoundException(
                    "[SusSetup] Starter~ is incomplete — run Tools~/refresh-starter-generated.ps1 in sus-core.");

            WriteIfMissing(Path.Combine(projectUiRootAbs, "HomeScreen.sharq"), File.ReadAllText(sharqSrc));

            var genDir = Path.Combine(projectUiRootAbs, "Generated");
            Directory.CreateDirectory(genDir);
            WriteIfMissing(Path.Combine(genDir, "HomeScreen.g.cs"), File.ReadAllText(gcsSrc, Encoding.UTF8));
        }

        public static void CopyAppEntry(string projectUiRootAbs, string className, bool withExample, bool withCustomization)
        {
            var starter = GetStarterRoot();
            string templateName;
            if (!withExample)
                templateName = "MyApp.Run.cs.txt";
            else if (withCustomization)
                templateName = "MyApp.Customization.cs.txt";
            else
                templateName = "MyApp.Mount.cs.txt";

            var templatePath = Path.Combine(starter, templateName);
            if (!File.Exists(templatePath))
                throw new FileNotFoundException($"[SusSetup] Missing starter template: {templateName}");

            var text = File.ReadAllText(templatePath, Encoding.UTF8)
                .Replace("{{CLASS_NAME}}", className);
            WriteIfMissing(Path.Combine(projectUiRootAbs, className + ".cs"), text);
        }

        /// <summary>
        /// Regenerates <c>Starter~/Generated/HomeScreen.g.cs</c> from the committed .sharq
        /// (maintainers). Same generator as the AssetPostprocessor.
        /// </summary>
        [MenuItem("Window/SUS/Setup/Refresh Starter Generated", false, 61)]
        public static void RefreshStarterGeneratedMenu()
        {
            try
            {
                var starter = GetStarterRoot();
                var sharqPath = Path.Combine(starter, "HomeScreen.sharq");
                var content = File.ReadAllText(sharqPath);
                var model = SharqFileParser.Parse(content, sharqPath);
                if (string.IsNullOrEmpty(model.TemplateXml))
                {
                    EditorUtility.DisplayDialog("SUS", "HomeScreen.sharq has no <template>.", "OK");
                    return;
                }

                var csharp = BuildMethodGenerator.Generate(model);
                // Stable comment path for git diffs
                csharp = System.Text.RegularExpressions.Regex.Replace(
                    csharp,
                    @"// Auto-generated by SharqSourceGenerator from .*",
                    "// Auto-generated by SharqSourceGenerator from Editor/Setup/Starter~/HomeScreen.sharq");

                var outDir = Path.Combine(starter, "Generated");
                Directory.CreateDirectory(outDir);
                var outPath = Path.Combine(outDir, "HomeScreen.g.cs");
                File.WriteAllText(outPath, csharp, new UTF8Encoding(false));
                Debug.Log($"[SusSetup] Refreshed starter Generated: {outPath}");
                EditorUtility.DisplayDialog("SUS",
                    "Starter~/Generated/HomeScreen.g.cs refreshed.\nCommit it in the sus-core repo.",
                    "OK");
            }
            catch (System.Exception ex)
            {
                Debug.LogError($"[SusSetup] Refresh Starter Generated failed: {ex}");
                EditorUtility.DisplayDialog("SUS", "Refresh failed — see Console.", "OK");
            }
        }

        static void WriteIfMissing(string absPath, string content)
        {
            if (File.Exists(absPath)) return;
            Directory.CreateDirectory(Path.GetDirectoryName(absPath)!);
            File.WriteAllText(absPath, content, new UTF8Encoding(false));
        }
    }
}
